### ISSUE TITLE
 There is a bug about GetComponentImage's result

### ISSUE THREAD

**Issue by hanoilu** [tesseract-ocr/tesseract#1004]
------------------------
Hello!

### Environment

* **Tesseract Version**: 4.0
* **Platform**: windows 64bit

### Current Behavior:
I find that GetComponentImages of APIexample( https://github.com/tesseract-ocr/tesseract/wiki/APIExample ) have a bug when I use to recognize  **Chinese**. Through the test found that the box->x,y,h,w are not the segmentation coordinates of the real recognition results.

### Expected Behavior:  
 I want to find the coordinates of the character that really recognizes.
  I hope I can get the really box->x,y, of  character.

### Suggested Fix: 
sorry, I'm trying to solve.

And I find its segmentation of Chinese is not very good, and I want to know which parameters will affect the result.
Thank you！

**Comment by mmsouming** [comment]
Who are you




发自网易邮箱大师
On 06/21/2017 16:37, hanoilu wrote:

Hello!

Environment
Tesseract Version: 4.0
Platform: windows 64bit
Current Behavior:

I find that GetComponentImages of APIexample( https://github.com/tesseract-ocr/tesseract/wiki/APIExample ) have a bug when I use to recognize Chinese. Through the test found that the box->x,y,h,w are not the segmentation coordinates of the real recognition results.

Expected Behavior: I want to find the coordinates of the character that really recognizes.

I hope I can get the really box->x,y, of character.

Suggested Fix: sorry, I'm trying to solve.

And I find its segmentation of Chinese is not very good, and I want to know which parameters will affect the result.
Thank you！

**Comment by mmsouming** [comment]
who are you ,My English is not very good

At 2017-06-21 16:37:50, "hanoilu" <notifications@github.com> wrote:


Hello!

Environment
Tesseract Version: 4.0
Platform: windows 64bit
Current Behavior:

I find that GetComponentImages of APIexample( https://github.com/tesseract-ocr/tesseract/wiki/APIExample ) have a bug when I use to recognize Chinese. Through the test found that the box->x,y,h,w are not the segmentation coordinates of the real recognition results.

Expected Behavior: I want to find the coordinates of the character that really recognizes.

I hope I can get the really box->x,y, of character.

Suggested Fix: sorry, I'm trying to solve.

And I find its segmentation of Chinese is not very good, and I want to know which parameters will affect the result.
Thank you！

**Comment by zdenop** [comment]
Can you provide testing case for this issue (image and simle code test, result you are comparing...)?

**Comment by amitdo** [comment]
@zdenop, please delete the 2 'Who are you' comments.

**Comment by zdenop** [comment]
Closed because of missing input from reporter
