### ISSUE TITLE
There is about a question of GetComponentImages

### ISSUE THREAD

**Issue by hanoilu** [tesseract-ocr/tesseract#1005]
------------------------
Hello!

### Environment

* **Tesseract Version**: 4.0
* **Platform**: windows 64bit

### Current Behavior:
I find that GetComponentImages of APIexample( https://github.com/tesseract-ocr/tesseract/wiki/APIExample ) have a bug when I use to recognize  **Chinese**. Through the test found that the box->x,y,h,w are not the segmentation coordinates of the real recognition results.

### Expected Behavior:   I want to find the coordinates of the character that really recognizes.
  I hope I can get the really box->x,y, of  character.

### Suggested Fix: sorry, I'm trying to solve.

And I find its segmentation of Chinese is not very good, and I want to know which parameters will affect the result.
Thank you！

**Comment by mmsouming** [comment]
Ok，稍等




发自网易邮箱大师
On 06/21/2017 16:40, hanoilu wrote:

Hello!

Environment
Tesseract Version: 4.0
Platform: windows 64bit
Current Behavior:

I find that GetComponentImages of APIexample( https://github.com/tesseract-ocr/tesseract/wiki/APIExample ) have a bug when I use to recognize Chinese. Through the test found that the box->x,y,h,w are not the segmentation coordinates of the real recognition results.

Expected Behavior: I want to find the coordinates of the character that really recognizes.

I hope I can get the really box->x,y, of character.

Suggested Fix: sorry, I'm trying to solve.

And I find its segmentation of Chinese is not very good, and I want to know which parameters will affect the result.
Thank you！
