### ISSUE TITLE
Listing languages fails if eng.traineddata is missing

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#1073]
It is not possible to list the available languages if `eng.traineddata` is missing.

Tesseract unnecessarily wants to load that file and terminates with a failure message before looking for other language files.

**Comment by chrismamo1** [comment]
This appears to be caused by the return value for `TessBaseAPI::Init` being checked before listing the available languages. Because you shouldn't be passing a language if you just want to list the ones available, Tesseract defaults to English, which causes the function mentioned above to fail. In #1076 I just moved the check a few lines down.

**Comment by stweil** [comment]
Thanks, that pull request fixed the issue (not perfectly, because Tesseract still prints an error message, but sufficiently).

**Comment by chrismamo1** [comment]
Yeah, the error message is problematic. Ideally, there should be a way to initialize the API object while specifying that you don't actually intend to recognize on anything. I'll look into this, but it might be a while since I just started digging through the Tesseract source.
