### ISSUE TITLE
当图片只有单字中文时候一般没法识别

### ISSUE THREAD

**Issue by yhfwww** [tesseract-ocr/tesseract#1079]
当图片只有单字中文时候一般没法识别~
Before you submit an issue, please review [the guidelines for this repository](https://github.com/tesseract-ocr/tesseract/blob/master/CONTRIBUTING.md).

Please report an issue only for a BUG, not for asking questions.

Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.

Please delete this text and fill in the template below. 

------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**:

**Comment by huanpenglee** [comment]
请给出一些重现资料，比如：需要识别的那个单字图片，你使用的tesseract版本和traneddata，以及使用场景。你是用编译好的二进制tesseract命令还是使用API在你的程序里识别，如果使用的是命令，请贴上你的命令行参数，如果是使用的SDK，请贴上代码。目前的master版本无论是在命令行下还是SDK模式下都运行的挺好。

**Comment by huanpenglee** [comment]
如果是4.0版的命令行工具，请试一下：`tesseract input.tif output -psm 8 -oem 1`

**Comment by zdenop** [comment]
Please report issue in English

**Comment by amitdo** [comment]
Translation via Google Translate

@yhfwww commented 

>When the picture is only a single word when the Chinese generally can not identify

@huanpenglee commented

>Please give some reproduction of the information, such as: need to identify that word picture, you use the tesseract version and traneddata, and use the scene. Do you use the compiled binary tesseract command or use the API to identify in your program, if you are using the command, please paste your command line parameters, if it is using the SDK, please paste the code. The current version of the master, whether it is in the command line or SDK mode are running very good.
If it is version 4.0 of the command line tool, please try: tesseract input.tif output -psm 8 -oem 1

**Comment by hannixu** [comment]
可以参数训练的文档，做自己的训练库来增强识别能力。



hanni_xu
 
发件人： yhf
发送时间： 2017-08-14 09:11
收件人： tesseract-ocr/tesseract
抄送： Subscribed
主题： [tesseract-ocr/tesseract] 当图片只有单字中文时候一般没法识别 (#1079)
当图片只有单字中文时候一般没法识别~
Before you submit an issue, please review the guidelines for this repository.
Please report an issue only for a BUG, not for asking questions.
Note that it will be much easier for us to fix the issue if a test case that
reproduces the problem is provided. Ideally this test case should not have any
external dependencies. Provide a copy of the image or link to files for the test case.
Please delete this text and fill in the template below.


Environment
Tesseract Version: 
Commit Number: 
Platform: 
Current Behavior:
Expected Behavior:
Suggested Fix:
