### ISSUE TITLE
Warning in pixReadMemJpeg

### ISSUE THREAD

**Issue by fairsky66** [tesseract-ocr/tesseract#112]
I got a new issue after installation and specified tessdata directory:
<pre>
localhost $ > tesseract /scratch/NBS/code/captcha/test.jpeg hahaha
Tesseract Open Source OCR Engine v3.05.00dev with Leptonica
Warning in pixReadMemJpeg: work-around: writing to a temp file
</pre>

pixReadMemJpeg, what is that? How to solve it?

**Comment by peirick** [comment]
The warning comes from the used leptonica library. You can find a copy of the leptonica source with the file that logs the warning here:

https://github.com/peirick/leptonica/blob/8498455d4bbc9df94f767bb030df1f6c37071c69/leptonica/src/jpegio.c

As far as I see its just because the leptonica library is built without the HAVE_FMEMOPEN definition. So It uses a temporary file instead of memory maped files. This is not tragic.

**Comment by fairsky66** [comment]
Thanks for this information. I have just installed tesseract with pip install pytesseract, then everything seems fine.
