### ISSUE TITLE
DotProductAVX can't be used on Android error on Windows

### ISSUE THREAD

**Issue by Molochnik** [tesseract-ocr/tesseract#1151]
While trying to recognize my test 2pages tiff file the test program stops on the breakpoint:
```
double DotProductAVX(const double* u, const double* v, int n) {
  fprintf(stderr, "DotProductAVX can't be used on Android\n");
  abort();
}

```
I  use windows.
I tested a small PNG file with the same result

**Comment by amitdo** [comment]
Which version of Windows?

MSVS? MinGW ? Cygwin?
 
How did you build it?

**Comment by Molochnik** [comment]
WIn10, MSVC 2017, built the same way as 3.04 and 3.05, they both work perfect.

**Comment by stweil** [comment]
So you compiled `arch/dotproductavx.cpp` and `arch/dotproductsse.cpp` with the same compiler options as always, namely without the options for AVX / SSE 2.1. Then it is normal that your program will crash  on computers with AVX / SSE 2.1 support. Tesseract 3.05 and earlier versions did not have those source file – that's why you now have a problem.

**Comment by Molochnik** [comment]
Looks like I added a little more files in MSVC project than required. 
Now I copied 3.05 MSVC project to 4.00 directory, removed some missed cpp files and added one by one cpp files from lstm and arch directories. Everything went fine and no error occured.
Looks like simple adding all source files didn't work in this case.
