### ISSUE TITLE
ERROR when using API

### ISSUE THREAD

**Issue by hoangtocdo90** [tesseract-ocr/tesseract#1208]
------------------------

### Environment

* **Tesseract Version**: 
* **Commit Number**: 
* **Platform**: 

### Current Behavior:
Tesseract baseAPI
`pixWriteAutoFormat("F:/test.jpg", croppedImage);
		Pix* test = pixRead("F:/test.jpg");
		api.SetImage(test);
		api.Recognize(0);
		char *value2 = api.GetUTF8Text();`

ERROR : 
`Error in pixCreateHeader: height must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made
Error in pixClipRectangle: pixd not made`

Note : Input image is exist !

### Suggested Fix:
Leptonical build

**Comment by amitdo** [comment]
The error messages come from Leptonica.

**Comment by zdenop** [comment]
This is not tesseract issue.

**Comment by hoangtocdo90** [comment]
This is Tesseract issue .
This is my command line output : 
I'm trying to edit cppan.yml clean cppan cache cmake cache an rebuild but still error
dependencies:
        pvt.cppan.demo.danbloomberg.leptonica: 1.74.2

I'm tested in 1.74.2,1.74.3,1.74.4?
Can you explain why this is not tesseract issue?

PS E:\TesseractOpenCV\Build\tesseract\build64\bin\Release> .\tesseract.exe --tessdata-dir F:/ F:\1.png F:/abc
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Error in pixCreateHeader: height must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made
Error in pixClipRectangle: pixd not made
Error in pixCreateHeader: height must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made

**Comment by zdenop** [comment]
it is not teaseract issue:
1. message comes from leptonica.
2. it complains about wrong input.
3. it seems that you did not trace where is problem.


Dňa 14. 11. 2017 7:32 používateľ "hoangtocdo90" <notifications@github.com>
napísal:

This is Tesseract issue .
This is my command line output :
I'm trying to edit cppan.yml clean cppan cache cmake cache an rebuild but
still error
dependencies:
pvt.cppan.demo.danbloomberg.leptonica: 1.74.2

I'm tested in 1.74.2,1.74.3,1.74.4?
Can you explain why this is not tesseract issue?

PS E:\TesseractOpenCV\Build\tesseract\build64\bin\Release> .\tesseract.exe
--tessdata-dir F:/ F:\1.png F:/abc
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica

Error in pixCreateHeader: height must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made
Error in pixClipRectangle: pixd not made
Error in pixCreateHeader: height must be > 0
Error in pixCreateNoInit: pixd not made
Error in pixCreate: pixd not made

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/1208#issuecomment-344159713>,
or mute the thread

**Comment by amitdo** [comment]
Try to isolate the problem and find out which function/method call triggers the error.

Start by calling only Leptonica functions:

>pixWriteAutoFormat("F:/test.jpg", croppedImage);
Pix* test = pixRead("F:/test.jpg");

**Comment by hoangtocdo90** [comment]
#1223
