### ISSUE TITLE
TODO: AVX512

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#1266]
Tesseract 4.00 has code to detect AVX512 (F,BW), but currently there is no actual optimized code that uses AVX512  instructions.

**Comment by stweil** [comment]
I'm afraid that it would not help very much as the dot product calculation is already limited by the memory speed (that's why SSE and AVX don't differ very much).

The bad news is that Tesseract speed is also affected by [Spectre](https://en.wikipedia.org/wiki/Spectre_(security_vulnerability)): it runs slower on latest Debian Stretch kernels.

**Comment by amitdo** [comment]
>The bad news is that Tesseract speed is also affected by Spectre: it runs slower on latest Debian Stretch kernels.

How many percent slower?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/issues/943#issuecomment-303239929

>AVX2 and AVX512 extend the integer operations beyond the ones available on SSE (not on base AVX) and may make it worth it, when I get machine with AVX512.
