### ISSUE TITLE
jpn lang recognize error

### ISSUE THREAD

**Issue by sxch775** [tesseract-ocr/tesseract#146]
tesseract will recognize digit '1' to char 'ー'
![2014](https://cloud.githubusercontent.com/assets/15794980/11084642/e905b71c-8878-11e5-9928-3c66d2379190.png)
this image will be recognize to "20ー4"

**Comment by atuyosi** [comment]
@sxch775 

It is caused by  jpn.unicharambigs (line 23?).
So, you may fix this file, and substitute it.

1. extract jpn.unicharambigs file( or [github](https://github.com/tesseract-ocr/langdata/tree/master/jpn) ).  
  ```
  $ combine_tessdata -e tessdata/jpn.traineddata jpn.unicharambigs
  ```
2. edit jpn.unicharambigs  
 ref. https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#the-last-file-unicharambigs
3. substitute  
  ```
  $ combine_tessdata -o tessdata/jpn.traineddata jpn.unicharambigs
  ```
4. use new jpn.traineddata  

If you want more accuracy, you can see my pull request [fix wrong type indicator(for jpn) by atuyosi · Pull Request #17 · tesseract-ocr/langdata · GitHub](https://github.com/tesseract-ocr/langdata/pull/17 "fix wrong type indicator(for jpn) by atuyosi · Pull Request #17 · tesseract-ocr/langdata · GitHub")

Thanks.

**Comment by sxch775** [comment]
do it will be fixed in next release?

**Comment by sxch775** [comment]
where can i download the tessreact 3.04 excuteable file for windows

**Comment by tfmorris** [comment]
@sxch775 Why did you close this issue?  Have you resolved the problem on your own?  It looks like @atuyos 's pull request is still open and hasn't been merged yet.
