### ISSUE TITLE
unicharambigs man page missing v2 format

### ISSUE THREAD

**Issue by tfmorris** [tesseract-ocr/tesseract#165]
The man page for the unicharambigs file format only includes documentation on the v1 format, not the v2 format (and is missing a description of the first line which is used for version identification).

https://github.com/tesseract-ocr/tesseract/blob/master/doc/unicharambigs.5.asc

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract#the-unicharambigs-file

has info about both formats

**Comment by zdenop** [comment]
Which file use unicharambigs file v2?

**Comment by Shreeshrii** [comment]
I think Ray had updated the documentation (couple years back??). From what
I understand from it unicharambigs file could be either in v1 format or v2
format.

- sent from my phone. excuse the brevity.

On 01-Sep-2016 12:38 AM, "zdenop" <notifications@github.com> wrote:

Which file use unicharambigs file v2?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/165#issuecomment-243868362>,
or mute the thread

**Comment by zdenop** [comment]
I did not find (in langdata repository) language that use v2 of unicharambigs... So I am not sure if it make sense to write docs for it (=> propagate it) if it is not used (=> not tested).

**Comment by Shreeshrii** [comment]
Thanks for checking langdata from 3.04.

Ray is the best person to answer whether v2 has been used/tested for any
languages.

Also, there was supposed to be a new release as per tutorial at DAS2016. Do
you know when that will be and what is included in it?

- sent from my phone. excuse the brevity.

**Comment by zdenop** [comment]
I hear something like end of September 2016, but you never know ;-) It will big update (probably we will drop support of compilers nor support c++11)...

**Comment by Shreeshrii** [comment]
@zdenop Thanks for the update.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
@zdenop Any update regarding 4.0 release? Thanks!

**Comment by amitdo** [comment]
The lstm engine does not use the unicharambigs file.
