### ISSUE TITLE
[Feature Request] Add kMinCharactersToTry as a user parameter

### ISSUE THREAD

**Issue by imswebra** [tesseract-ocr/tesseract#1729]
Currently the `kMinCharactersToTry` value is hardcoded within the tesseract master branch, as seen below.

https://github.com/tesseract-ocr/tesseract/blob/a0291c765129af3217540a0fb344d8bbedad8333/src/ccmain/osdetect.cpp#L39-L40

Allowing this value to be user configurable (without a recompile) enables more flexibility when it comes to working with small data sets, especially images that are computer generated with very little, if any, background noise.

For example, the 4x4 number array below only outputs empty pages because of this value (`"Too few characters. Skipping this page"`). Larger arrays, like the 6x6 one below, continue to work fine.

![4x4array](https://user-images.githubusercontent.com/29715203/42194875-4620d64a-7e33-11e8-9dad-b0b5e0c0533f.png)

&nbsp;

![6x6array](https://user-images.githubusercontent.com/29715203/42195020-12eeeb62-7e34-11e8-999e-f609cfcd9909.PNG)

There is a post in the google group claiming to have already requested this feature [here,](https://groups.google.com/d/msg/tesseract-ocr/ZRQ6dgUPx8E/tUGGxlotAAAJ) though I couldn't find any GitHub issues documenting the request, so I created this one.

Further evidence of demand for such a feature can be found earlier in the [same google group post,](https://groups.google.com/d/msg/tesseract-ocr/ZRQ6dgUPx8E/3eB-aoc9ah8J) and also in the rOpenSci R tesseract bindings repository, [here](https://github.com/ropensci/tesseract/issues/13) and [here.](https://github.com/ropensci/tesseract/issues/15)

**Comment by amitdo** [comment]
There is a reason why it's hardcoded.
For detection of the script a smaller number of chars won't work well.

Are some of the images you want to ocr rotated (90/180/270 degrees)?  



.

**Comment by imswebra** [comment]
My assumption was that the limit was coded especially with scanned, physical documents in mind. If there exists a blank page between a title page and the beginning of a book, for example, without the threshold tesseract might falsely recognize a few characters that are actually just scan noise. Therefore, by introducing the kMinCharactersToTry value, we increased accuracy by correctly assuming the page was blank.

However, in a scenario such as that first 4x4 matrix where we are dealing with computer generated images that are perfect and without noise, such a check is not increasing accuracy but instead limiting usability. I agree that a small number of characters won't necessarily work well, but _any_ recognized characters is better than refusing to output anything at all. Implementing a parameter with the same default value does not affect the out-of-the-box accuracy, but does give tesseract some more flexibility in terms of its application.


Also, no, I won't be using rotated images. Care to explain why you asked?

**Comment by amitdo** [comment]
>no, I won't be using rotated images. Care to explain why you asked?

kMinCharactersToTry is used by the OSD feature, which tries to detect the script and orientation of the image.

Tesseract can be used with several modes (--psm N in the command line). Only 3 out 13 of them active the the OSD feature (0, 1, 12 ).

Do you use pdf / hocr output? They also activate OSD by default.

Without OSD, tesseract is not limited to a minimum number of characters, and can even detect a single character.

**Comment by imswebra** [comment]
Okay cool, I didn't know it was used exclusively by the OSD part. Thanks!

Even though my hurdles have been overcome, I would still argue that it may be a good improvement for the sake of someone in my shoes that needs the OSD. I'll leave the ticket open for now unless you think otherwise.

**Comment by imswebra** [comment]
Sorry for the late reply.

> kMinCharactersToTry is used by the OSD feature, which tries to detect the script and orientation of the image.

If this is the case, shouldn't `--psm 3` (the default option) return an output?
For example, using the two images I provided in the original post, when I run `Tesseract-OCR\tesseract bigtest.png stdout` and `Tesseract-OCR\tesseract smalltest.png stdout`, the first yeilds an output as expected, but the second gives me `Empty Page!! Empty Page!!`.

Any ideas if this is not due to kMinCharactersToTry?

**Comment by amitdo** [comment]
>Any ideas if this is not due to kMinCharactersToTry?

It's not, because the command you gave does not activate OSD.

**Comment by imswebra** [comment]
After playing around with a larger sample size of screenshots, it seems that tesseract just doesn't want to play nice with the array style formatting.

When all of the characters are in line (like in the larger image provided), it has no problem. I can crop down that larger image to a 2x2 and still be successful. However, when characters are not in line, like when a three character number (143 or -45) is above a single character number (0 or 7), the results aren't nearly as pretty. The way that these arrays are generated also means that the spacing between distinct numbers isn't always the same depending on what other length numbers are in the array.

Unless you have anything to add, feel free to close this issue. Thanks for your help.

**Comment by CanadianHusky** [comment]
I would have liked to see the constants 

```
const int kMinCharactersToTry = 50; 
const int kMaxCharactersToTry = 5 * kMinCharactersToTry;
```
acccessible from the command line as well. 

I read all comments above and understand the reasoning but I had to compile the source myself, about a year ago, with modified kMin/kMax values (kMin = 10 / kMax = 25 x kMax ) because in the scenario described below nothing else worked for me:

I need to feed tiny images into the OCR engine. 
The content may have characters, just a few, sometimes just 2-3 letters, or maybe even no characters
-PSM mode is set to 0 because the only goal is to detect Text Rotation. No Actual OCR will be performed in this scenario.
the content is 0 / 90 / 180 / 270 rotated. The primary goal is to detect the correct rotation to make it "right reading" at the fastest possible speed. The performance is critical and even 10 ms slower or faster counts.
The goal is to determine the rotation of much larges files (and a large number of them) by taking a few "samples" at various (intelligently selected) spots and corners. Feeding the whole image into the OCR engine is not feasible because these are very large, high resolution files and choke the processing speed and kill the memory.

with my modified source, which is based on v4.0.0-alpha.20170703, the orientation detection works perfect because I changed the constants.

With the original build, the code exits with "too few charactars".....----Yes I know..I still want to know their orientation!

The source receives regular updates and it is quite an effort to recompile it.
I would appreciate if the developers can reconsider the decision to leave those values hardcoded. There are over 200 other settings in nearly every other category. 

Respectfully, The argument that states

> There is a reason why it's hardcoded.
> For detection of the script a smaller number of chars won't work well
> 
is weak because an advanced user would know what he/she is doing. Configuring the existing command line values wrongly will also cause the engine to perform false. It should be the responsibily of the user to ensure the settings match his/her desired intend. 

If there is a smarter way to detect orientation of the majority of text of a TIF (group4, monochrome, compressed) image with approx 30,000x50,000 pixels that is under 100 ms total processing time, I would love to find out. 
With the algorithm I applied, I get the performance and accuracy I need but I am missing on the updates and future development progress of the otherwise great library. 

Thank you kindly

**Comment by Shreeshrii** [comment]
As you can see there are limited active contributors to the project and current focus is on bug fixes so that 4.0.0 can be released.
May I suggest that you submit a PR with the suggested changes for this feature request.
Thanks.

**Comment by amitdo** [comment]
>-PSM mode is set to 0 because the only goal is to detect Text Rotation. No Actual OCR will be performed in this scenario.

This feture is implemented by using the legacy legacy **OCR** engine in 4 directions.

**Comment by CanadianHusky** [comment]
I have compiled the current master branch myself. 
Unless I am making a mistake in my test, the current/latest code is performing far worse than v4.0.0-alpha.20170703 in the following scenario and with the following files

command line : 
`tesseract --psm 0 "C:\temp\input.png" "C:\output"`

**result with v4.0.0-alpha.20170703**
```
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 1.76
Script: Latin
Script confidence: 35.83

```
**result with master**
```
Page number: 0
Orientation in degrees: 180
Rotate: 180
Orientation confidence: 0.30
Script: Latin
Script confidence: 4.44
```

The result form the current master branch is complete nonsense for the attached input image
Anybody want to verify and/or comment about what happened here ?

![input](https://user-images.githubusercontent.com/35332003/45922910-02e0b500-bee1-11e8-99f8-2f2f13edf61e.png)

**Comment by CanadianHusky** [comment]
further info : result with version v4.0.0-beta.1.20180608 is correct 

```
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 1.76
Script: Latin
Script confidence: 35.83

```

I am pretty sure, someone broke something in the code after 20180608 release

**Comment by Shreeshrii** [comment]
@zdenop Please label as `Feature Request`.

**Comment by stweil** [comment]
@Shreeshrii, did you mean the label `enhancement`? Or do we already use `Feature Request`?

**Comment by zdenop** [comment]
We do not have ` Feature Request` label, IMO enhancement is `sufficient `;-

**Comment by Shreeshrii** [comment]
It is up to @zdenop to decide.  There are many feature requests by users but not all may agreed to as enhancements to be done by developers.

OK, I see now the list of labels being used currently. Thanks for pointing it out.

**Comment by imswebra** [comment]
@Shreeshrii @zdenop Should the title of the feature request be edited to "[Enhancement] ..." instead of the current "[Feature Request] ..." ?

**Comment by zdenop** [comment]
No. keep it as it is.

**Comment by amitdo** [comment]
>We do not have Feature Request label, IMO enhancement is sufficient ;-)

Now we have :-)
https://github.com/tesseract-ocr/tesseract/labels/feature%20request

**Comment by zdenop** [comment]
I found I can rename label ;-)

**Comment by stweil** [comment]
Yes, the GitHub standard _enhancement_ label is now _feature request_. I don't know whether this is really better - personally I like standards (until there is something much better).

**Comment by amitdo** [comment]
'feature request' is a much more common term used by users.

**Comment by amitdo** [comment]
Strangely, if you put the mouse pointer over the 'feature request' label, a tooltip  with the text 'enhancement' pops up.

**Comment by stweil** [comment]
I think @zdenop moved the old value from the label name to the description. That description is empty by default, but can be set to any text.

**Comment by CanadianHusky** [comment]
Respectfully, the last 12 messages are by 5 different people and about the workings of the tagging system on the site. 
By the time that discussion got carried out, the mentioned variable probably could have been turned into a command line argument and the issue resolved.
I feel the recent discussion here got completely off topic.
Kind Regards.

**Comment by zdenop** [comment]
Opensource is about contributions. That discussion is about tool that use contributors of this project. 
How did you contribute to this project, that you are judging their conversion???

**Comment by CanadianHusky** [comment]
I contributed by alerting the development Team that no meaningful OSD detection on mixed content as shown in the samples is possible with the most recent version and that it is a regression compared to an earlier build where this has been working fine. 
I furthermore contributed by showing the source of the problem and what needs to be done to correct the issue.

**Comment by stweil** [comment]
The regression is caused by commit 27ce472666a6332f38888cd6855e1162fb82c729 which enforced the use of `osd.traineddata`. Here `tesseract --psm 0` was called without specifying a language, so in the past `eng.traineddata` was used implicitly, while now `osd.traineddata` is used.

I recently learned that people want to use `--psm 0` with an explicit language parameter. Of course Tesseract then can only detect the orientation, but not the script.

So my suggested solution would be to change the code and either use the explicit language specified by the user or use `osd.traineddata` as the default. Then the old behavior can be reproduced by adding `-l eng`. Would that be acceptable, or are there other suggestions?

**Comment by CanadianHusky** [comment]
perfectly fine for me.
thank you

**Comment by amitdo** [comment]
>[Feature Request] Add kMinCharactersToTry as a user parameter

I now think it's OK to implement this Feature Request.

**Comment by stweil** [comment]
Pull request #1944 allows doing orientation detection with an explicitly given traineddata file.

**Comment by zdenop** [comment]
```
tesseract.exe i1729.png - --psm 0 -c min_characters_to_try=5
Warning. Invalid resolution 0 dpi. Using 70 instead.
Page number: 0
Orientation in degrees: 0
Rotate: 0
Orientation confidence: 0.02
Script: Cyrillic
Script confidence: 6.67
```

Enjoy.

**Comment by Shreeshrii** [comment]
>I would have liked to see the constants
const int kMinCharactersToTry = 50; 
const int kMaxCharactersToTry = 5 * kMinCharactersToTry;
acccessible from the command line as well.

@zdenop Have you made both of these constants available?

**Comment by zdenop** [comment]
only minimum....

**Comment by CanadianHusky** [comment]
For my purposes only minimum is sufficient, and I believe most others will
only need the minimum value as well but while the code is still fresh in
your mind you may want to include max value as well.

If there is performance to be gained by telling the engine to stop looking
after x chars it may be useful.

Thank you for looking back into this. Much appreciated
