### ISSUE TITLE
Recognition on x32

### ISSUE THREAD

**Issue by qb1t0** [tesseract-ocr/tesseract#1838]
------------------------

### Environment

* **Tesseract Version**: 4.0.0-beta4
* **Platform**: Ubuntu 16.04 x32 

### Current Behavior:
Bad text recognition on x32-bit server ;C
### Expected Behavior:
Good recognition.
### Suggested Fix:
Additional building flags ?

**Comment by stweil** [comment]
Support for x32 might indeed be interesting, because it should be significantly faster than 32 bit code and could even be slightly faster than 64 bit code because of better cache usage. I expect that it will require some work on the Tesseract code base to fix all portability issues. See https://wiki.debian.org/X32Port for a few first hints.

**Comment by stweil** [comment]
@qb1t0, is the recognition on other installations better? Could you provide an example for the bad text recognition (image, command line, results)?

**Comment by stweil** [comment]
With the test image from https://github.com/tesseract-ocr/tessdata/issues/108, I get the same results for x32 and for x86_64 when I add `--psm 6`.

There is a difference when running `tesseract test.tif -`: x32 shows the well know assertion `contains_unichar_id(unichar_id):Error:Assert failed:in file src/ccutil/unicharset.h, line 509`

**Comment by Shreeshrii** [comment]
@zdenop Please label as `Feature Request`.

**Comment by stweil** [comment]
I think it can be closed, as x32 and x86_64 deliver the same results.
