### ISSUE TITLE
HOCR to output font name

### ISSUE THREAD

**Issue by armadilloOCR** [tesseract-ocr/tesseract#186]
Hi all, 

I am trying to use Tesseract's HOCR output functionality to generate an html file that includes all of the word font attributes - most of important of which is font_id.  From first glance, it looks like I will have to write a custom HOCR script with the result_Iterator to make this work.  

Any tips on getting HOCR output with font ID info without having to rewrite the GetHocrText function?

Thanks !!!

**Comment by tfmorris** [comment]
Your better off asking questions on one of the mailing lists where more people will see it.  I only happened to stumble across this because I was looking at the hOCR code.

The current hOCR renderer already has the capability to output font information, including name.  It just needs to be enabled with a config parameter.

@zdenop please close this

**Comment by amitdo** [comment]
Please use [Tesseract users forum](https://groups.google.com/d/forum/tesseract-ocr) for support.
