### ISSUE TITLE
Unable to extract white text with tesseract

### ISSUE THREAD

**Issue by kkurni** [tesseract-ocr/tesseract#1913]
------------------------

### Environment

* **Tesseract Version**: 4.0 LSTM
* **Platform**: Mac & Ubuntu 18.04

### Current Behavior:
I notice tesseract does not detect a white text with any dark background.
Similar to this question: https://stackoverflow.com/questions/50853660/unable-to-extract-white-color-text-in-tesseract

### Expected Behavior:
Extract the white text

### Suggested Fix:

Is there an easy fix for this case?

**Comment by alexmyczko** [comment]
I wonder if simply inverting the images would help?

**Comment by kkurni** [comment]
Unfortunately not, because Inside the image it contains black text and white text.

I tried to do binarization, but it reduces the quality even further and still does not detect well on white text. using Pillow - image.convert('L')

**Comment by zdenop** [comment]
Report is not correct: `tesseract Vigcd.jpg -` produce this output:

```
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 349
FOCUS

LEADERS CONCENTRATE
SINGLE-MINDEDLY ON ONE
THING- THE MOST IMPORTANT
THING, AND THEY STAY AT IT
UNTIL ITÔÇÖ'S COMPLETE.

Brian Tracy

BRIANTRACY.COM
```
which is not 100% correct, but it is difficult to reach 100% in OCR. Other image (`tesseract XDJFq.jpg -`) is more difficult basically because of using outline font (and changing color for text is not helping) :

```
Warning. Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 731
Detected 16 diacritics
oming together

IE@UNNUN@QQQ

keeping together is

PROERESSws

working together is

SUJ(C(CESSQQQÔÇś
```
Such images need to prepocessing (r.g. try to eliminate background, passing to tesseract only text regions with the same font...) 

I do not think there something we can do in tesseract (engine) here.
