### ISSUE TITLE
CMake fails to configure project for MinGW-w64

### ISSUE THREAD

**Issue by Reaper1121** [tesseract-ocr/tesseract#1988]
### Environment

* **Tesseract Version**: Latest Source including Release Candidates for 4.0
* **Commit Number**: e371a9e49d00b87d2b994a186c8f066cc7fc59b0
* **Platform**: Windows 7 64-bit

### Current Behavior: 
CMake (GUI) fails to configure the project for MinGW-w64, same error occurs on older versions of CMake (GUI) as well.

**CMake version**: CMake 3.13.0-rc1

**Error provided by CMake**:
`CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.13/Modules/FindPkgConfig.cmake:39 (find_package_handle_standard_args)
  CMakeLists.txt:96 (find_package)`

**Output file provided by CMake**: https://pastebin.com/EBUSakxX

### Expected Behavior: 
CMake (GUI) should be able to configure the project for MinGW-w64 and then generate it.

### Suggested Fix: 
Unknown, nothing worked so far.

**Comment by zdenop** [comment]
Please read error message carefully: `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`. Do you have installed pkgconfig?

**Comment by Reaper1121** [comment]
Yes, that was something I was missing, I downloaded a really old build I was able to find, now it says I need "lept" library, which I have downloaded and installed that into the correct lib and header folders. 

Still no luck, it still says that the library is missing, I am guessing pkg-config is not working properly? 
I tried out the cppan solution (I never heard of), but that fails because its unable to find some CXX_COMPILER "cl" command? My compilers are GCC and G++ (No MSYS2) and if I do it from CMake GUI, it has no problem detecting the compilers it needs.

**Comment by zdenop** [comment]
Well, building on windows is tricky:
 - cmake with cppan build it tested, working and supported... with VS Studio... (`cl` is command line compiler from Visual studio)
 - cross-compilling on linux should work (with autotools): [Mannheim University](https://digi.bib.uni-mannheim.de/tesseract/) is doing like that

If you choose to go other way you will be alone probably  :-( - because of capacity of tesseract contributors... Anyway I would like to see windows build with cmake and clang 7 at least because of openmp 4 support... If you do it with MinGW-w64 it would be great too - just share your experience.

Maybe easier way for you could be msys+MinGW-w64 => and using autotools. I did it in past on my old windows computer. How hard it is depends on your experience with building from source.

**Comment by Reaper1121** [comment]
It appears that I won't be able to build it, I have **0 experience on linux** (I am a **windows** user). 
I am in a desperate need of a good **OCR** library but you don't always get what you want, it would be great to see if someone provided a **prebuilt package containing the needed libtesseract static library**. 
I'll look into some wrapper like C# for the moment being, thank you for your help, but I think my only option is to look somewhere else.

**Comment by Ortega-Dan** [comment]
Just in case this helps someone ... installing the prebuild package from https://digi.bib.uni-mannheim.de/tesseract/ will give you the libtesseract dynamic linked library in the installation directory ... by default in C:\Program Files\Tesseract-OCR
