### ISSUE TITLE
Line Indentation is ignored, no way to enable it.

### ISSUE THREAD

**Issue by mickaelistria** [tesseract-ocr/tesseract#2071]
I'm using Tesseract 3.05.02 (packaged in Fedora 29), and I'm using it to read text in a code editor (same monospace font, different colors and styles -monospace/italic-)

The command I'm using is `tesseract -c preserve_interword_spaces=1 -psm6 <input> <output>`. I need plain text, not HTML.
I didn't find a way to preserve the line indentation, even a relative one.
So if I read a text editor that contains
```
a {
    color: red;
}
```
Tesseract tells me it
```
a {
color: red;
}
```
and ignores to whitespaces before the line.

It would be a good addition to have an option like `preserve_prefix_whitespaces=1` to get the prefix indentation part of the text.

**Comment by stweil** [comment]
PDF and hOCR output have text positions, so that requirement would only make sense for text output. I know no other OCR software which preserves leading whitespace, and even if it were implemented, it would not fit your needs because it could output relative whitespaces, but not the exact number of blanks needed for code indentation.

Why don't you use a code formatter to fix the indentation after the OCR?

**Comment by mickaelistria** [comment]
relative whitespaces would be perfect in my case.
I'm using Tesseract to test the rendering of a text editor I'm working on (Eclipse IDE in that case), and I would like from a given editor to automatically take a screenshot of the text area (that's provided by internal APIs) and then invoke OCR and compare what I get from OCR matches the text I want to see in the editor, ideally including leading whitespaces (even if that's just relative).
