### ISSUE TITLE
Missing special characters in desired_characters file (Swedish)

### ISSUE THREAD

**Issue by aslamy** [tesseract-ocr/tesseract#2075]
The file langdata/swe/desired characters does not contains many of the important special characters like "@".

**Comment by stweil** [comment]
Then please report for https://github.com/tesseract-ocr/langdata and/or https://github.com/tesseract-ocr/langdata_lstm.

You should also be more specific because for example I don't know Swedish, so I cannot guess what "many of the important special characters" means. Try to make a list, or even better try to prepare a pull request which adds the missing characters.

**Comment by aslamy** [comment]
Thank you!

**Comment by stweil** [comment]
It's also possible to use `script/Latin` for Swedish. That should contain all characters.

**Comment by Kalle12345** [comment]
@stweil thank you for your suggestion.
I tried script/Latin , but it was worst. nothing was correct. So if swedish can't identifiera @ is because of desired_characters folder missing that character? And when we put that character in desired_characters folder, we have to do a new training for the Swedish language?

**Comment by stweil** [comment]
See https://github.com/tesseract-ocr/langdata_lstm/issues/4.
