### ISSUE TITLE
Win10 cygwin64 building fail

### ISSUE THREAD

**Issue by yunnet** [tesseract-ocr/tesseract#2379]
Environment：
```
win10 x64
cygwin64 3.0.6-1
```
Current Behavior:
Open Cygwin Terminal and Type the following Codes:
git clone https://github.com/tesseract-ocr/tesseract.git
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
mkdir build
cd build
cmake ..
cmake --build .
cd ../
cd ../
cd tesseract
mkdir build
cd build
cmake .. -DLeptonica_DIR=/pkg/leptonica/build
```
Configuring tesseract version 4.1.0-rc1-254-g3c734e...
C++11 support enabled...
-- Found LibArchive: /usr/local/lib/libarchive.dll.a (found version "3.3.4")
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file limits.h
-- Looking for include file limits.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file memory.h
```

cmake --build .
```
....
/pkg/tesseract/src/ccmain/paragraphs.cpp: In the function ‘void tesseract::InitializeRowInfo(bool, const tesseract::MutableIterator&, tesseract::RowInfo*)’:
/pkg/tesseract/src/ccmain/paragraphs.cpp:2458:10: error：‘isascii’ not declared in this scope
          isascii(text[trailing_ws_idx - 1]) &&
          ^~~~~~~
make[2]: *** [CMakeFiles/libtesseract.dir/build.make:615：CMakeFiles/libtesseract.dir/src/ccmain/paragraphs.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:105：CMakeFiles/libtesseract.dir/all] error 2
make: *** [Makefile:117：all] error 2

```

**Comment by zdenop** [comment]
For cygwin64  use autotools.

**Comment by egorpugin** [comment]
I think we may put conditions in cmake to fail when unsupported platform is used.

**Comment by stweil** [comment]
I tried to reproduce this, but could not because Cygwin only has an older version of cmake:

    $ cmake ..
    CMake Error at CMakeLists.txt:11 (cmake_minimum_required):
      CMake 3.8 or higher is required.  You are running version 3.6.2

**Comment by zdenop** [comment]
I was able to reproduce problem with cmake and cygwin I plan to fix it after 4.1 release (there is some consolidation with cppan build)
IMO we need to decrease required version of cmake (to 3.6?), but I remember correctly it will touch c++17 detection....

**Comment by egorpugin** [comment]
Why cygwin at all?
Tess is perfectly fine with MSVC.

**Comment by zdenop** [comment]
IMO cygwin is most fastest/easiest solution if somebody wants to have linux tools on Windows (including shell for training scripts).  On other hand it provides most slowest compiling process I've experienced. So if somebody just want to make quick test and build the latest tesseract it could be reasonable option. For such case installing MSVC colossus is no option (and community version does not run in some corporate accounts/environment)

Anyway it depends what user need. Definitely there are more options for on Windows ([mingw](https://mingw-w64.org/doku.php), [clang](https://clang.llvm.org/get_started.html), [intel c++](https://software.intel.com/en-us/c-compilers), [MSVC](https://visualstudio.microsoft.com/downloads/)...)  and it does not seems like a big issue to support them in cmake.

**Comment by egorpugin** [comment]
I'm asking because people are still trying to build tess+lept manually and skipping most of dependencies on such setups (win, cygwin), so they get wery limited even maybe now working builds.

CMake could take deps unix-style with pkg-config on cygwin, but not on win.
Hard way is to build all deps, force things to use each other and so on.

Instead it's possible to 1) combine cmake with sw, 2) use only sw, 3) combine cmake with cppan (working, but deprecated), 4) use cppan only (working, but deprecated too).

**Comment by Shreeshrii** [comment]
There is a community member who packages tesseract for cygwin. Search the
forum for contact info. I am sure he will build new version when released.

**Comment by zdenop** [comment]
It is great to have cppan/sw especially because of training tools. But a lot of people are using [vckpkg](https://github.com/microsoft/vcpkg/tree/master/ports/tesseract). Or cross-compiled version from linux. Some other peopple suggest to use [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux).

If you need to integrate tesseeract to other project you do not need to care much about other dependencies - you can open image standard way (e.g in python, or QT, or opencv)
OpenCV use cmake and it integrate tesseract/leptonica (I do not think they will integrate sw or cppan build). So there is a bunch of options and it is good: user can select something that fits their needs. Of course there should be some default/preferred way which is at the moment autotools or cppan/sw on windows.

**Comment by zdenop** [comment]
I was able to build the recent tesseract code with the latest cygwin and autotools on windows 64bit:
```
$ cygcheck -c cygwin
Cygwin Package Information
Package              Version        Status
cygwin               3.2.0-1        OK

$ uname -r
3.2.0(0.340/5/3)

$ c++ --version
c++ (GCC) 11.2.0
```

**Comment by zdenop** [comment]
cmake build in the same environment failed...
