### ISSUE TITLE
Feature request: embed pdf.ttf to tesseract library

### ISSUE THREAD

**Issue by zdenop** [tesseract-ocr/tesseract#2551]
If somebody want to distribute just tesseract library, also tessdata/pdf.tff must be shipped for providing searchable pdf functionality.

IMO [pdf.ttf](https://github.com/tesseract-ocr/tesseract/blob/master/tessdata/pdf.ttf) is the only file from[ tessdata directory](https://github.com/tesseract-ocr/tesseract/tree/master/tessdata), that can not be replaced (all config files are just list of variables that can be handled now with -c option of tesseract executable or API).

**Comment by jbreiden** [comment]
That makes it a little harder to change the font, but we haven't changed it
for years.
So sounds reasonable to me. Are you thinking of uint8 pdf_ttif[] = { 0x00,
0x01, ... } ?

**Comment by stweil** [comment]
Is the current Tesseract library useful without any external data, not even traineddata? I could imagine a Tesseract library which gets external data from the Internet on demand (maybe with local caching), but that is not the current state.

For `pdf.ttf` an integration into the code could be fine because it is small (only 572 bytes), and the codesize could be reduced by the file handling overhead.

**Comment by zdenop** [comment]
You need traningdata for tesseract initialization, so without them library does not work.
Other topics is OSD: I found quite a lot of people use tessseract of orientation and deskew detection... Is more accurate than routine available in leptonica...
