### ISSUE TITLE
In case we provide Russian language as Input and content is English, it converts English characters in Russian.

### ISSUE THREAD

**Issue by divyangashah** [tesseract-ocr/tesseract#2691]
### Environment

* **Tesseract Version**: 4.0.1
* **Platform**: Windows, 64-bit 

### Expected Behavior:
It should not convert English letters to Russian
### Suggested Fix:
Is there any way we can detect English characters in English only? if not, is there any way we can use English as by default language.

**Comment by stweil** [comment]
That's the expected behavior. If you use a language model which only knows the letters A, B and C, it will either detect nothing or A, B and C, causing an 8 interpreted as B or maybe an O as C.

The simple solution for your case is to choose a model which knows both English and Russian (like `script/Cyrillic`) or to call Tesseract with two models, one for English and one for Russian.

**Comment by divyangashah** [comment]
@stweil actually I am loading cyrillic/russian model only which causes english language content to convert in russian
