### ISSUE TITLE
Tesseract fails to load any languages with --oem 0 option

### ISSUE THREAD

**Issue by zafalija** [tesseract-ocr/tesseract#2835]
### Environment

* **Tesseract Version**: 4.1.0
* **Platform**: Linux parrot 5.3.0-3parrot3-amd64 #1 SMP Parrot 5.3.9-3parrot3 (2019-11-23) x86_64 GNU/Linux

### Current Behavior:
tesseract myimg.png output --oem 0 gives the following error:

> Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

### Expected Behavior:
To use --oem 0 without errors
### Suggested Fix:
I suspect that tesseract isn't able to find languages, however `tesseract --list-langs` prints eng and osd.
This is the path to my tessdata folder.
/usr/share/tesseract-ocr/4.00/tessdata

**Comment by stweil** [comment]
There is a simple answer to your question: don't use advanced options like `--oem 0` unless you are an advanced user. Please use the user forum for questions.

The right answer is that `eng` exists, but does not support `--oem 0`, so Tesseract refuses to use it.

This problem is reported here very often. Maybe you want to provide a patch for Tesseract to give a better error message?

**Comment by stweil** [comment]
See [list of similar reports](https://github.com/tesseract-ocr/tesseract/issues?utf8=%E2%9C%93&q=is%3Aissue+%22Tesseract+couldn%27t+load+any+languages%21%22+%22--oem+0%22).

**Comment by tandelDipak** [comment]
Found the solution in forum. Check out this discussion https://groups.google.com/g/tesseract-ocr/c/KKTiag0VCFE/m/A4jpS6i6CwAJ

Let me know whether it solves your issue or not.
