### ISSUE TITLE
TesseractConfig.cmake is not generated correctly during cmake/build

### ISSUE THREAD

**Issue by Moldoteck** [tesseract-ocr/tesseract#2883]
The problem is with quotes, you should add them because cmake can't gracefully handle config without them and i can't include headers in my project. Tested in master branch
### Current Behavior:
set(Tesseract_INCLUDE_DIRS C:/Program Files (x86)/tesseract/include;C:/Program Files (x86)/tesseract/include/tesseract)

### Expected Behavior:
set(Tesseract_INCLUDE_DIRS "C:/Program Files (x86)/tesseract/include;C:/Program Files (x86)/tesseract/include/tesseract")

### Suggested Fix:
add quotes

**Comment by zdenop** [comment]
Please provide minimal example that demonstrate problem.

**Comment by Moldoteck** [comment]
> 
> 
> Please provide minimal example that demonstrate problem.

Ok:
*******************
```
unzip tesseract-master
download sw + add it to path + sw setup
mkdir build
use Cmake-gui -> configure -> generate project in build folder
build and install the project
```
*******************
add tesseract in your project by adding next lines in yours CMajeLists.txt:
*******************
```
find_package(Tesseract REQUIRED)
include_directories(${Tesseract_INCLUDE_DIRS})
target_link_libraries (YourProj PRIVATE ${Tesseract_LIBRARIES} )
```
*******************
Now use cmake for yours project
*******************
```
mkdir build for yours project
use Cmake-gui -> configure 
```
*******************
You will get this warnings:
```
CMake Warning (dev) at C:/Program Files (x86)/tesseract/cmake/TesseractConfig.cmake:39:
  Syntax Warning in cmake code at column 50
...
CMake Warning (dev) at C:/Program Files (x86)/tesseract/cmake/TesseractConfig.cmake:39:
  Syntax Warning in cmake code at column 91

```

*******************

How to fix:

Path in line 39 in  C:\tesseract-master\build\TesseractConfig.cmake should be in quotes:
Old:
`set(Tesseract_INCLUDE_DIRS C:/Program Files (x86)/tesseract/include;C:/Program Files (x86)/tesseract/include/tesseract)`
New:

`set(Tesseract_INCLUDE_DIRS "C:/Program Files (x86)/tesseract/include;C:/Program Files (x86)/tesseract/include/tesseract")`

**Comment by essamzaky** [comment]
I received the same error when build OpenCV using CMake GUI
but adding quotes does not solve the problem
I got the following error

"""
**_CMake Error at D:/Tutorial/Git/tesseract/build32/inst/cmake/TesseractConfig.cmake:39 (set):
  Syntax error in cmake code at

    D:/Tutorial/Git/tesseract/build32/inst/cmake/TesseractConfig.cmake:39

  when parsing string

    D:\Tutorial\Git\tesseract\build32\inst/include;D:\Tutorial\Git\tesseract\build32\inst/include/tesseract
  Invalid character escape '\T'.
Call Stack (most recent call first):
  D:/Tutorial/Git/opencv_contrib-master/modules/text/cmake/init.cmake:8 (find_package)
  cmake/OpenCVModule.cmake:312 (include)
  cmake/OpenCVModule.cmake:378 (_add_modules_1)
  modules/CMakeLists.txt:7 (ocv_glob_modules)_**
"""
it seems Cmake recognize '\T' as character scape

So i used slash '/' instead of '\'  and updated line 39 in 
D:/Tutorial/Git/tesseract/build32/inst/cmake/TesseractConfig.cmake

Update line 39
set(Tesseract_INCLUDE_DIRS "D:/Tutorial/Git/tesseract/build32/inst/include;D:/Tutorial/Git/tesseract/build32/inst/include/tesseract")
Old line 39
set(Tesseract_INCLUDE_DIRS "D:\Tutorial\Git\tesseract\build32\inst\include;D:\Tutorial\Git\tesseract\build32\inst\include\tesseract")

**Comment by zdenop** [comment]
Can you please check the latest code? I see there:
```
set_and_check(Tesseract_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")

```

**Comment by amitdo** [comment]
No response to @zdenop request.
