### ISSUE TITLE
tesseract fails with "Illegal instruction" in AVX code, when built on a different machine

### ISSUE THREAD

**Issue by mikegerber** [tesseract-ocr/tesseract#2911]
### Environment

* **Tesseract Version**: 4.1.1
* **Platform**: `Linux b-pc30533 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Current Behavior:
I built Tesseract in a Docker container, and in Travis. When I run the tesseract binary in the container on my local machine, I get the error "Illegal instruction", gdb output:

~~~
$ gdb --args tesseract OCR-D-IMG_00000024.tif tess
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tesseract...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/tesseract OCR-D-IMG_00000024.tif tess
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Page 1
Detected 4466 diacritics

Program received signal SIGILL, Illegal instruction.
0x00007ffff7b1b64d in tesseract::DotProductAVX(double const*, double const*, int) () from /usr/local/lib/libtesseract.so.4.1.1
(gdb) quit
A debugging session is active.

▹‧‧‧‧‧‧‧Inferior 1 [process 137] will be killed.

Quit anyway? (y or n) y
~~~
(This was run using gdb inside a running Docker container)

If I run it using `-c dotproduct=sse` it works:
~~~
$ gdb --args tesseract -c dotproduct=sse OCR-D-IMG_00000024.tif tess
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tesseract...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/tesseract -c dotproduct=sse OCR-D-IMG_00000024.tif tess
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Page 1
Detected 4466 diacritics
[Inferior 1 (process 143) exited normally]
(gdb) quit
~~~

The local machine supports AVX/AVX2:
~~~
$ tesseract --version
tesseract 4.1.1
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
~~~
~~~
$ grep avx2 /proc/cpuinfo  | head -1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
~~~

### Expected Behavior:
tesseract should not crash with Illegal instruction.

**Comment by mikegerber** [comment]
Exact build commands:
https://github.com/mikegerber/my_ocrd_workflow/blob/master/Dockerfile#L38-L42

If I built the same container locally (so same Ubuntu 18.04 base image, same build commands) I do not get this problem. So maybe it something about the CPU differences between the machine used by Travis and mine.

**Comment by stweil** [comment]
That's an interesting case. So your local machine supports AVX, but not in a Docker container.

This might be fixed in Git master (commit 57ff90687db9f9569f7837b3d3f709dafb3d00f5). Could you run your test with Git master or apply that commit to 4.1.1 before running the test?

If Docker containers don't support AVX, that will result in reduced performance of course.

**Comment by mikegerber** [comment]
I do not see this as "So your local machine supports AVX, but not in a Docker container.", because if I use the binary built by alex-p (PPA https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr), I don't get the problem:

~~~
root@145ad7abe111:/data/actevedef_718448162.first-page/OCR-D-IMG# tesseract --version
tesseract 4.1.1-rc2-21-gf4ef
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
root@145ad7abe111:/data/actevedef_718448162.first-page/OCR-D-IMG# tesseract OCR-D-IMG_00000024.tif tess
Tesseract Open Source OCR Engine v4.1.1-rc2-21-gf4ef with Leptonica
Page 1
Detected 4466 diacritics
~~~

Am I interpreting this correctly, that it is using AVX2?

**Comment by amitdo** [comment]
Mike, please listen to Stefan, he knows what he's talking about.

**Comment by stweil** [comment]
> If I use the binary built by alex-p, I don't get the problem.

@mikegerber, like other Linux distributions Alex builds with autogen.sh / configure / make, while you use cmake / make, so the different result must be caused by the different build rules.

The cmake build sets compiler options for the whole code depending on the host CPU (see https://github.com/tesseract-ocr/tesseract/blob/4.1/cmake/OptimizeForArchitecture.cmake). So if the build host supports AVX512, that would be enabled and it might happen that the compiler generates code which will fail on a CPU without AVX512 support.

The autoconf build sets SSE / AVX / AVX2 options only for some functions (independent of the build host). Those functions are choosen at runtime depending on the features of the CPU.

Meanwhile we know that AVX2 support not only requires a CPU which can execute AVX2 instructions, but also requires an operating system which handles those instructions and the related CPU registers correctly. That was fixed in the commit mentioned above.

If you are interested in finding the reason for the illegal instruction trap, I'd disassemble the crashing function in GDB and look at the address shown to see which kind of instruction is there.

If you just want to have a working Docker, I suggest to switch from cmake to autoconf build. OCR-D/ocrd_all also uses the [autoconf build for Tesseract](https://github.com/OCR-D/ocrd_all/blob/master/Makefile#L419).

**Comment by mikegerber** [comment]
Alright 'cmake vs autoconf' seems to explain this and the target CPU does indeed not support AVX-512. Thanks for the info!

I'm moving towards using packages in my Docker build anyway - to save time - and the alex-p packages work fine, so I'm satisfied :+1:

**Comment by mikegerber** [comment]
> Mike, please listen to Stefan, he knows what he's talking about.

Why wouldn't I?

**Comment by mikegerber** [comment]
I've updated the title to make this issue easier to find.

**Comment by amitdo** [comment]
CMake should do what Autotools does, at least for Linux, macOS, Cygwin, MinGW-w64.

Untill this happens, I suggest to document all differences between the two build system.
