### ISSUE TITLE
tesseract prints "Estimating resolution as " (takes >1 second to print this line) even if I pass SetVariable("user_defined_api", "70")

### ISSUE THREAD

**Issue by lucaszanella** [tesseract-ocr/tesseract#2925]
I'm calling tesseract with 

`SetVariable("user_defined_api", "70")`

It supressed 

`Warning: Invalid resolution 0 dpi. Using 70 instead.`

however I still see

`Estimating resolution as 304`

which takes more than 1 second to print, so I need to get this out

**Comment by lucaszanella** [comment]
Please take a look on how "Estimating resolution" is killing performance

https://photos.app.goo.gl/UKKTKSiAnQT4mB876

**Comment by zdenop** [comment]
Read your post. Again and again and again until you find YOUR mistake. If it does not help, try to replicate problem with tesseract executable ;-)

**Comment by lucaszanella** [comment]
@zdenop I think you are talking about my typo in `api`. Unfortunately it's not in my code, just here.

Somebody told me to use 

`tess.SetVariable("user_defined_dpi", "71");`

and it worked. Don't know why. Posting here to help someone.

**Comment by zdenop** [comment]
Yes, but there are more problems:
* finding reason / relevant part of tesseract code for your issue is easy
* instead of understanding your problem you write issue, you made screen cast, you made stackoverflow post...
* you ignored guidance for issue tracker: for support you have to use tesseract user forum
* your approach is wrong: you did not try to understanding suggestion from SO, you just used it. If somebody will suggest you to run `rm -fr /` will you do it? This approach is dangerous not only in programming but also in real life.
