### ISSUE TITLE
Cmake build is broken

### ISSUE THREAD

**Issue by egorpugin** [tesseract-ocr/tesseract#2986]
Someone changed avx/fma code, so cmake build is outdated.
I took a look, but not sure about good fix.

**Comment by zdenop** [comment]
[seems to be related](https://travis-ci.org/github/tesseract-ocr/tesseract/builds) to my commit https://github.com/tesseract-ocr/tesseract/commit/acaa90c971c9b5b27555f63bd20fe7903f66ef4d where I restricted compiler definition for "dotproduct" to arch directory instead of  using them globally .

It seem strange for me, because there should be no effect on arch directory files, that seem to produce error. 
I tested it on windows with cmake&clang and it worked for me.  I just tested with clang&msvc and it failed.
Also [travis reports](https://travis-ci.org/github/tesseract-ocr/tesseract/builds/687742872) that it works for cmake and clang (on Mac) but it fails with cmake and g++ (Ubuntu)., so actually it looks like compiler specific problem.

**Comment by egorpugin** [comment]
Oh, yes, we noticed that on MSVC build.

**Comment by zdenop** [comment]
msvc (should) works (+clang), but gcc resists - it looks like that it requires global compiler definition (e.g.-D__AVX__ ...), but this is what I tried to avoid, optimization is use only on arch file, so it can be enabled/disabled runtime.

Unfortunately I can not find computer where I can replicate problem (I found one with SSE4.1 and cmake build there worked...) to find good solution.
Anyway lets keep this issue open, until it is solved for gcc too.

**Comment by zdenop** [comment]
When I tried to implement NEON code on my Raspberry PI I found out that `set_source_files_properties` has not effect on build, so [this is probably reason](https://github.com/tesseract-ocr/tesseract/blob/a06d0d84497d7b0ad905c298bf5bacf8f7063c69/CMakeLists.txt#L402-L420) why gcc build with make fails (and I am still wondering why msvc and clang build works...). Unfortunately I have not time to dig in this more next week or two...
