### ISSUE TITLE
Debugger Viewer doesn't work, can't connect to ScrollView server

### ISSUE THREAD

**Issue by ellislau** [tesseract-ocr/tesseract#3000]
### Environment

* **Tesseract Version**: 4.1.1
* **Commit Number**: 4.1.1 Release
* **Platform**: MacOS Catalina 10.15.5, Darwin Kernel Version 19.5.0

### Current Behavior:
When using the parameter ```inter``` or ```interactive_display_mode```, the application hangs.

### Expected Behavior:
The debugger viewer window should open.

### Suggested Fix:
The issue seems to be that ScrollView uses java.net.ServerSocket which always uses TCP, whereas the SVNetwork logic in svutil.cpp may look for either a TCP or UDP socket. In my case, it was looking for a UDP socket and was not able to successfully connect. Tentatively, it seems that passing an addrinfo ```hints``` object that sets ```ai_protocol``` to IPPROTO_TCP was sufficient to work around the problem (https://www.man7.org/linux/man-pages/man3/getaddrinfo.3.html).

**Comment by zdenop** [comment]
please provide full information how to reproduce your problem.

**Comment by ivan-alaffia** [comment]
Seconded - the `inter` flag hangs indefinitely for me both on 4.1.1 and 5.0.0alpha, but works correctly on 4.0.0.

Platform: MacOS Big Sur 11.1

Steps to reproduce:
1. Build Tesseract from source following [this guide](https://github.com/tesseract-ocr/tesseract/issues/1453):
```
export JAVA_VERSION=1.8
export PATH=/usr/local/bin:/usr/local/lib:/usr/local/sbin:$PATH

git clone https://github.com/tesseract-ocr/tesseract/
cd tesseract
./autogen.sh
./configure LDFLAGS=$LDFLAGS \ 
    CPPFLAGS=$CPPFLAGS \
    PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/leptonica/lib/pkgconfig  \
    --enable-debug
make -j
sudo make install
make training
cd java
SCROLLVIEW_PATH=$(pwd) JAVA_VERSION=1.8 make ScrollView.jar
```
2. Download English trained data following https://tesseract-ocr.github.io/tessdoc/Data-Files.html
3. Download [phototest.tif](https://github.com/tesseract-ocr/test/blob/master/testing/phototest.tif)
4. From the root `tesseract` directory, run `TESSDATA_PREFIX=$(pwd)/tessdata tesseract phototest.tif test1 segdemo inter`, following the [Debug Viewer guide](https://tesseract-ocr.github.io/tessdoc/ViewerDebugging.html).

**Comment by tfmorris** [comment]
I just ran into this as well and it took a fair amount of debug setup and head scratching to figure out what was going on, particularly since both sides of the communication are error free, but nothing happens because they're talking past each other. Lucky issue 3000!

@ellislau Thanks for reporting the problem. Your analysis was spot on. Here's what it looks like on my system:
```
$ java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 -Xms512m -Xmx1024m -Djava.library.path=$SCROLLVIEW_PATH -cp $SCROLLVIEW_PATH/ScrollView.jar:$SCROLLVIEW_PATH/piccolo-1.2.jar:$SCROLLVIEW_PATH/piccolox-1.2.jar com.google.scrollview.ScrollView &
Listening for transport dt_socket at address: 1044
Socket started on port 8461
$ sudo lsof -i :8461
COMMAND    PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
tesseract 3155 tfmorris    6u  IPv6 0xfb0634dc780d2b35      0t0  UDP localhost:57154->localhost:8461
java      3177 tfmorris    8u  IPv6 0xfb0634dca1d53275      0t0  TCP *:8461 (LISTEN)
```
Note that the display server is listening on TCP port 8461 while the client is connected to UDP port 8461, which, of course, isn't the same thing at all.

I put PR #4162 up with a tested fix which works for me. @ellislau I suspect you had the same fix. If you state your suggestion in the form of a PR, that'd probably get things fixed quicker. The project operates with pretty much a skeleton crew, so every little contribution helps.
