### ISSUE TITLE
[tesseract] read_params_file: Can't open pdf/txt.

### ISSUE THREAD

**Issue by hongyi-zhao** [tesseract-ocr/tesseract#3411]
See [here](https://github.com/jbarlow83/OCRmyPDF/issues/773) for more detailed info of this problem.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue. We do not support 3rd party project. Reproduce problem directly in tesseract

**Comment by hongyi-zhao** [comment]
Got it. The problem is caused by the submodules of [tessdata](https://github.com/tesseract-ocr/tessdata) haven't been updated successfully, and can be fixed by the following commands issued from the tessdata's local repo root directory:

```
$ git submodule deinit --force .
$ git submodule update --init --recursive --remote
```

**Comment by hongyi-zhao** [comment]
The problem has been solved, see [here](https://github.com/tesseract-ocr/tesseract/issues/3411#issuecomment-830723153) for more detailed descriptions.

**Comment by reportaman** [comment]
@hongyi-zhao Thanks! that worked

**Comment by alexHxun** [comment]
I got a same error and i resolved it by git clone https://github.com/tesseract-ocr/tessconfigs.git in the tessdata folder

**Comment by yosamshiyam** [comment]
Sorry, I'm not too computer savvy as some folks here (am on a mac).  But hongyi-zhao stated that “he problem is caused by the submodules of [tessdata](https://github.com/tesseract-ocr/tessdata) haven't been updated successfully, and can be fixed by the following commands issued from the tessdata's local repo root directory:” and then followed by subsequent code...

how exactly does one get to 'tessdata's local repo root directory' on a mac, using homebrew.  I'm not very good at this stuff as you can tell but essentially I'm getting the exact read_params_ issue and don't really know how to get this resolved on my end.  I can't seem to use ocrmypdf with any language, so I'm figuring files are not where they should be.
