### ISSUE TITLE
[Clarification request/Suggestion] TESSDATA_PREFIX as (optional) configure option

### ISSUE THREAD

**Issue by Wikinaut** [tesseract-ocr/tesseract#368]
I am asking why there is not specific ./configure variable for the location of the language data (i.e. what can be also done with TESSDATA_PREFIX environment variable).

What I suggest is a possibility to hardcode the path the language data while compiling tesseract-

**Comment by zdenop** [comment]
Language data path is hardcoded in linux build see:

- https://github.com/tesseract-ocr/tesseract/blob/master/ccutil/Makefile.am#L6
- https://github.com/tesseract-ocr/tesseract/blob/master/ccutil/mainblk.cpp#L77

**Comment by Wikinaut** [comment]
@zdenop do you mean, TESSDATA_PREFIX follows the optional datadir option ?

**Comment by zdenop** [comment]
Best way is to test it ;-).

**Comment by jbreiden** [comment]
There is. Debian uses -DTESSDATA_PREFIX=/usr/share/tesseract-ocr/

**Comment by Wikinaut** [comment]
@jbreiden just as an proposal to add a comment in the ```configure --help``` that datarootdir must contain the /tessdata directory unless this is defined by the TESSDATA_PREFIX


Current --help shows:
```
  --datarootdir=DIR     read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
```

**Comment by jbreiden** [comment]
zdenko is the build king, he can decide such things

**Comment by stweil** [comment]
@Wikinaut, Tesseract for Windows uses a different method to find `tessdata`. A fixed TESSDATA_PREFIX would not work on Windows, because there is no fixed installation path.

**Comment by amitdo** [comment]
All the ways to set  `TESSDATA_PREFIX` should be documented in the wiki.

**Comment by zdenop** [comment]
TESSDATA_PREFIX is set (via autotool variable @datadir@) to directory where autotools installed tessdata (at the time when tessdata were part of tesseract library repository). Because there was no installation on Windows (Visual studio) TESSDATA_PREFIX is (was?)  set to "./" 
There is [logic](https://github.com/tesseract-ocr/tesseract/blob/master/ccutil/mainblk.cpp#L58) of how to find tessdata location:
1. Use tessdata prefix from the command line.
2. Use tessdata prefix from the environment.
3. (Windows):  Look for tessdata in directory of executable.
4. Use tessdata prefix which was compiled in.

If you need to add something to wiki or configure help, you are welcomed to send PR ;-)

**Comment by Wikinaut** [comment]
@jbreiden wrote
> There is. Debian uses -DTESSDATA_PREFIX=/usr/share/tesseract-ocr/

just for the record:

On my debian 8 system, configured with `./configure --enable-debug` only, tesseract wants to have the language files in 
`/usr/local/share/tessdata`
