### ISSUE TITLE
Feature Request: allow mulitple files for stdin

### ISSUE THREAD

**Issue by dnnspaul** [tesseract-ocr/tesseract#3720]
### Environment

* **Tesseract Version**: 5.0.1
* **Commit Number**: latest
* **Platform**: Linux dpaul-desktop 5.11.0-46-generic 51~20.04.1-Ubuntu SMP Fri Jan 7 06:51:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Current Behavior:
Using `cat file1.jpg file2.jpg | tesseract - stdout` only handles file1.jpg. File2 is being ignored.
I know about filelists, but using a filelist is no option because of pre-processing; using cat is just a demonstration of the problem/bug.

### Expected Behavior:
Both files are processed.

**Comment by stweil** [comment]
Combining image files with `cat` does not give a valid file which can be processed by any software.

I did not understand why a filelist is not an option for you. Could you please explain that a bit more?

**Comment by zdenop** [comment]
We will happily review your patch for this.

**Comment by amitdo** [comment]
Tesseract supports streaming only for the filelist feature. Also, you have to explicitly set the `stream_filelist` variable to `true`.

Check `ProcessPagesInternal(()` and  `ProcessPagesFileList()` in `/stc/api/baseapi.cpp`.

**Comment by thelulzy** [comment]
> Tesseract supports streaming only for the filelist feature.

I'm confused. Wasn't the whole point of issue https://github.com/tesseract-ocr/tesseract/issues/233#issue-134928135 regarding the streaming of multipage TIFFs? 

From the original issue:
> The current multi-page TIFF handling is seriously sub-optimal. First, it unnecessarily reads the entire file into memory which can tie up many MB of memory unnecessarily when pages are being processed in a streaming fashion

A response regarding the state of streaming behavior at when the issue was raised:
https://github.com/tesseract-ocr/tesseract/issues/233#issuecomment-186502235
> the "streaming" support doesn't stream - at least for anything other than a list of file names. All other formats are read entirely into memory before any processing starts. That's a pretty narrow definition of streaming.

Here's the comment from @DanBloomberg I mentioned in my last post where he mentions how to use leptonica for the implementation of multipage tiff streaming in tesseract:
https://github.com/tesseract-ocr/tesseract/issues/233#issuecomment-203167825
> To implement this properly in tesseract, ***where you only want one image in memory at the same time***, use the same approach that I just did in pixReadMultipageTiff():
> ...
___
Is the inherent value of never writing a file to disk when doing OCR not apparent?

**Comment by amitdo** [comment]
>I'm confused.

It confusing indeed.

You missed some other points from issue #233:

>You are right, the streaming feature is super narrow. But it is important for book digitization.

>I think functionally it is exactly the same, except that a multipage TIFF **from a file** does not get buffered.

 >This patch reduces multipage TIFF seeks from O(n^3) to O(n),

**Comment by amitdo** [comment]
>Is the inherent value of never writing a file to disk when doing OCR not apparent?

Tesseract CLI supports this feature, using the stdin, but Just for a single page at a time, not multi-page input.

**Comment by amitdo** [comment]
>Is the inherent value of never writing a file to disk when doing OCR not apparent?

Tesseract CLI supports this feature, using the stdin.

it supports reading a single page image from the stdin, one page for each CLI invocation.

I think it also supports reading standard multi-page TIFs input from the stdin. For a book with a hundreds of pages it can be useful.

I say "I think..." because I didn't test this scenario.

**Comment by thelulzy** [comment]
> Tesseract CLI supports this feature, using the stdin.
> 
> it supports reading a single page image from the stdin, one page for each CLI invocation.

Fair enough, I've done so!

> I think it also supports reading standard multi-page TIFs input from the stdin.

You are correct, I've verified that above (https://github.com/tesseract-ocr/tesseract/issues/3720#issuecomment-3016008428), although as we've discussed it will drain the entire stream into memory before processing/outputting.

> For a book with a hundreds of pages it can be useful.

Unfortunately this means that for a piece of media with thousands of pages we may run into memory capacity limitations.

____

I'm curious how much overhead is introduced by re-initializing tesseract for every image rather than processing additional images using the same instance. I suppose I could attempt to test this using the multi-page TIF feature.

**Comment by thelulzy** [comment]
I decided to see how leptonica handles piped input streams. At least for multipage TIFs it seems to behave the same as tesseract; loading the entire pipe buffer into memory before doing any processing. Here's how I went about it:
```cpp
#include <format>
#include <string>
#include <iostream>
#include <leptonica/allheaders.h>
int main(int argc, char **argv) {
    l_uint8      *data;
    size_t       offset, size;
    PIX          *pix1;

    data = l_binaryReadStream(stdin, &size);
    offset=0;
    do {
        pix1 = pixReadMemFromMultipageTiff(data, size, &offset);
        if (!pix1) continue;
        pixWrite(std::format("extracted_tiff{}.tiff", offset).c_str(), pix1, IFF_TIFF);
        std::cout << std::format("Offset: {}", offset) << std::endl;
        pixDestroy(&pix1);
    } while (offset != 0);
    return 0;
}
```

This worked fine for a 50 page (1920x1080) multipage tiff, but failed for a 500 page one with the following:
```
Error in reallocNew: newdata not made
Error in bbufferExtendArray: new ptr array not returned
Segmentation fault (core dumped)
```

I presume within the [l_binaryReadStream](https://github.com/DanBloomberg/leptonica/blob/0473e44d435c25d29b3f4ad082d5ec79e656b181/src/utils2.c#L1369C1-L1369C19) call the `ftell()` call specifies that the stream is not seekable, thus resulting in the following logic which grows a byte array until it can fit the input stream:
```cpp
    bb = bbufferCreate(NULL, 4096);
    while (1) {
        navail = bb->nalloc - bb->n;
        if (navail < 4096) {
             nadd = L_MAX(bb->nalloc, 4096);
             bbufferExtendArray(bb, nadd);
        }
        nread = fread((void *)(bb->array + bb->n), 1, 4096, fp);
        bb->n += nread;
        if (nread != 4096) break;
    }
```
(I'm not actually sure why this was failing for me with larger multipage TIFs, as they were all well within my available memory)

While trying to figure out why the TIF isn't seekable and looking for a lower level solution I ended up exploring [libtiff](https://libtiff.gitlab.io/libtiff/libtiff.html), where I came across the following:
> The TIFF specification requires that all information except an 8-byte header can be placed anywhere in a file. In particular, it is perfectly legitimate for directory information to be written after the image data itself. **Consequently TIFF is inherently not suitable for passing through a stream-oriented mechanism such as UNIX pipes.**

If there is ever an effort to support multi-image input to tesseract (other than the current multipage-tiff functionality), it sounds as though it will be easier to do so with a format other than TIF.
___
I'm currently looking into ffmpeg itself to see if I can (possibly via the ffmpeg API) either pass some form of image object directly from the demuxer and/or encoder to tesseract (API) or utilize its underlying piped stream processing functionality to iterate over images which were output via image2pipe. 

Another option might be trying to fork leptonica to see if I can replace some of the bbuffer and reading logic with libavformat's AVOpenCallback, although I imagine the scope of that would be fairly large.

**Comment by amitdo** [comment]
What are you tring to OCR in the vidoes, captions?
