### ISSUE TITLE
Tesseract example fails to start with "ld-elf.so.1: /usr/local/lib/libtesseract.so.5: Undefined symbol "__kmpc_global_thread_num""

### ISSUE THREAD

**Issue by vmato** [tesseract-ocr/tesseract#3827]
Running Basic_example from https://tesseract-ocr.github.io/tessdoc/Examples_C++.html on FreeBSD 13.1 results following error:

`ld-elf.so.1: /usr/local/lib/libtesseract.so.5: Undefined symbol "__kmpc_global_thread_num"
`

------------------------

### Environment

* **Tesseract Version**: 5
* **Platform**: FreeBSD localhost 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

**Comment by zdenop** [comment]
duplicate to #3777

**Comment by vmato** [comment]
This https://github.com/tesseract-ocr/tesseract/issues/3827 is a tesseract issue. https://github.com/tesseract-ocr/tesseract/issues/3777 considered to be a third party's issue

**Comment by stweil** [comment]
It does not help to claim whether something is a Tesseract or third party issue. Both issues are duplicates because they report the same missing symbol. That symbol is not part of the Tesseract code. It is specific to FreeBSD code. Everyone who is using FreeBSD is welcome to suggest a solution. Please don't expect help from the few volunteers who work on Tesseract and don't have FreeBSD (and the time) to do the work for you.

**Comment by zdenop** [comment]
This is not the tesseract issue, but the @vmato issue, who did not link all necessary libraries requested by FreeBSD with his custom project.
