### ISSUE TITLE
Tess4j 5.4.0 crashes under multi-threading environment in a predictable manner

### ISSUE THREAD

**Issue by vinodkrishram** [tesseract-ocr/tesseract#3911]
Hi There/[nguyenq](https://github.com/nguyenq):
Good Day!!!
You have done a wonderful job with Tesseract. Unfortunately, the JVM crashes in a predictable manner in a multi-threaded environment on linux . You had closed issue https://github.com/nguyenq/tess4j/issues/204 as NOT repeatable. Would it be possible for us to have a webex/collaborative session so that I can show the issue to you.

I am reaching out to you as last hope.

It would be helpful if you can spare sometime.

I can send you the core-dump if required and any other information you require to resolve this issue.

**Comment by stweil** [comment]
That report was for Tesseract 4.0, an old unsupported version. Now you write "Tesseract 5.4.0" in the subject, but our latest released code is 5.2.0. Please clarify.

**Comment by vinodkrishram** [comment]
I have downloaded 5.4.0 from maven. https://mvnrepository.com/artifact/net.sourceforge.tess4j/tess4j
Could you please check here

**Comment by stweil** [comment]
Please send a stack trace which shows that the problem is in the Tesseract code and which function causes it or try to reproduce the issue without tess4j by reducing it to pure C++ code or even better use the `tesseract` command line.

If that's not possible, you should report the issue to tess4j or try to find a solution yourself. I am sorry but we don't have the capacity to search for problems with third party software.

**Comment by amitdo** [comment]
No reply from the OP.
