### ISSUE TITLE
CI: SW jobs fail

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#3986]
@egorpugin

Egor, all SW jobs fail. There is a problem when building glib.  Please fix it.

**Comment by egorpugin** [comment]
I've made a fix, let's see.
https://github.com/tesseract-ocr/tesseract/actions/runs/3784158599

**Comment by amitdo** [comment]
Thanks.

**Comment by amitdo** [comment]
@egorpugin,

The SW job for Windows with VS 2022 failed in the last few days.

**Comment by egorpugin** [comment]
Should be fine now.

**Comment by amitdo** [comment]
@egorpugin,

The Windows job failed in the last few days.

**Comment by amitdo** [comment]
@stweil, @zdenop

IMO, we have a long standing principle issue with SW which is used in the CI for PRs and commits.

SW CI breaks regularly. Sometimes for weeks. It seems that Egor does not monitor it. See previous reports above and in issue #3861.\
Also see: https://github.com/tesseract-ocr/tesseract//actions/workflows/sw.yml?query=is%3Afailure \
Recent example: https://github.com/tesseract-ocr/tesseract/commit/566f97a29a4afd8

AFAICT, SW is not used by major open source projects except Tesseract and Leptonica. For most failures in SW CI, Egor is the only person that can fix them.

It's important that the CI won't break regularly and when it does break, it can be fixed by more than one individual in a timely manner. 

Therefore. I suggest to use Autotools (Linux. Mac) and CMake (Windows+MSVC) instead of SW for CI jobs triggered by PRs and commits. 

SW can still be used in a daily CI job for Windows+MSVC.

CC: @egorpugin

**Comment by stweil** [comment]
What are the reasons to use SW at all?

**Comment by egorpugin** [comment]
1.
Build is broken because I add new packages and they are broken sometimes on non commonly used configurations.
I've fixed windows build. The issue was in minor upgrade of icu (73.1->73.2).
To detect such issues I need some build farm for new packages. I have it in long-term todo list.

2.
About failing builds - I need to setup email notifications here.

3.
Why SW - I think CMake (Windows+MSVC) does not build training tools. Also workflow config, invocation is much easier.

4.
Ubuntu 20.04 fails - SW prefers the newest compiler for its own purposes (building configs), so if we want to restore that config, we can try to install newer compiler there. This still makes little sense because 'building on ubuntu 20.04' does not mean we support ubuntu - that means we support their compiler versions - what can be tested even on newer distributions.

**Comment by amitdo** [comment]
Recently, the sw badge says: 'failing' even when the sw jobs did not fail.

![Build status](https://github.com/tesseract-ocr/tesseract/workflows/sw/badge.svg)

https://github.com/tesseract-ocr/tesseract/actions/workflows/sw.yml

**Comment by stweil** [comment]
Yes, obviously something changed on GitHub. I just fixed that with commit 35d3a9c3550b52fea86bc5c69da079283fde4b79.

**Comment by stweil** [comment]
The sw jobs fail again sind May 1. Therefore I reopened this issue.
Would a weekly schedule or a manual trigger be sufficient?

**Comment by amitdo** [comment]
IMO, it's about time to finally wipe out SW entirely from this repo.

**Comment by egorpugin** [comment]
Hi,

I'll try fix it in the upcoming days.
Netherlands data center shut down my hosting provider for sw project with all data etc.
I'm trying to restore it to some backup point.
Please leave as is for now.

> IMO, it's about time to finally wipe out SW entirely from this repo.

Why?

**Comment by amitdo** [comment]
I explained what are the issues with SW multiple times over the past few years, including in this issue.

Why should Tesseract and Leptonica use a build system that no other major open source project use?!

**Comment by egorpugin** [comment]
> Why should Tesseract and Leptonica use a build system that no other major open source project use?!

They should not. Completely optional.
I'm ok with removing sw from cmake builds.

But leave ci jobs and `sw.cpp` as an alternative method.

**Comment by amitdo** [comment]
The option to use SW was removed from the CMake build.

Also, i changed the sw action to run once a week.
