### ISSUE TITLE
Text2image SIGSEGV on Linux

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#399]
>> @Shreeshrii @stweil : please create separate issue for command that crash on linux, so we can track it.

> That command also crashes with SIGSEGV on Linux. This is a bug which needs a fix.

`text2image --fonts_dir= --text ./langdata/san.training_text --outputbase san.exp-1 --ptsize=32 --strip_unrenderable_words --fontconfig_refresh_config_file=false --leading=32 --char_spacing=0.0 --exposure=-1 --find_fonts --min_coverage=.9 --degrade_image=1 --underline_start_prob=.05 --underline_continuation_prob=.01`

[Ref: Issue 396](https://github.com/tesseract-ocr/tesseract/issues/396)

**Comment by zdenop** [comment]
It does not crash on openSUSE linux:

[text2image_log.txt](https://github.com/tesseract-ocr/tesseract/files/443295/text2image_log.txt)

**Comment by stweil** [comment]
I noticed that the crash is a "feature", caused by an assertion if `langdata/san.training_text` does not exist. Tesseract forces a SIGSEGV for assertions to improve debug information.

IMHO missing data is a typical user error which should be reported, but not throw an assertion. So replacing the assertion by a conditional `tprintf(...); exit(1);` in `training/fileio.cpp` might be the correct solution. If you agree, I'll send a pull request.

**Comment by amitdo** [comment]
@stweil, right!
See #345 #349

**Comment by zdenop** [comment]
@stweil OK

**Comment by Shreeshrii** [comment]
FYI, in my testing on Windows 10, the crash was unrelated to 'langdata/san.training_text does not exist' since the file was very much there.

I will test further after new windows binary is made available with all these new patches.

Thanks for looking into this.

**Comment by stweil** [comment]
@amitdo, thanks for the pointers. PR #402 now does something similar for `fileio`.
