### ISSUE TITLE
CUDA GPU acceleration support 

### ISSUE THREAD

**Issue by ascyphermoonshot** [tesseract-ocr/tesseract#4129]
### Your Feature Request

The newer versions of Tesseract OCR use LSTM so implementing CUDA GPU acceleration support would be a good way to improve performance while leveraging a widely used architecture already tried for for NN tasks.

Ideally this should be available in both the command line and the API, preferably in all distributions, especially the versions available from package managers (apt).

**Comment by stweil** [comment]
That's correct. Do you want to implement it? Or do you know someone who can write the necessary code?

**Comment by stweil** [comment]
Ideally GPU acceleration should not be limited to NVIDIA GPUs. "CUDA" is specific to NVIDIA.

Note also that GPU acceleration is mainly required for the training process where it would really help to reduce the time which is required for a training.

GPU acceleration won't help much (if at all) with Tesseract text recognition. Mass OCR production with Tesseract is already very efficient on servers with many CPU threads.

**Comment by amitdo** [comment]
We have a tiny team of volunteers working to slowly improve the existing CPU-only code.

We don't plan to implement this feature request.

**Comment by jkarthic** [comment]
> GPU acceleration won't help much (if at all) with Tesseract text recognition.

@stweil Could you please clarify the above statement. Nvidia claims upto 140x faster throughput for LSTM models using cuda.
https://developer.nvidia.com/discover/lstm . Why will it not help for tesseract text recognition, since latest tesseract is based on LSTM?
Even if it provides 2x to 4x speed improvement, I will happily take it.

**Comment by stweil** [comment]
Tesseract does not use CUDA or other code which makes use of the NVIDIA GPU. As long as nobody adds that support, Tesseract always runs without GPU.

**Comment by jkarthic** [comment]
@stweil 
I think there is a misunderstanding on my question. I am aware of the current status of tesseract.
My question regarding your general statement of "GPU acceleration won't help much (if at all) with Tesseract text recognition". Why? Because nvidia claims otherwise for LSTM inference.

**Comment by stweil** [comment]
I noticed, too, that my answer was incomplete, and have added more text above. We have experience with kraken OCR which supports CUDA where we use the GPU only for training because the throughput for segmentation (also with AI model) and recognition is much better on the CPU. See [my related documentation](https://github.com/UB-Mannheim/digitue-gt/wiki#running-text-recognition).
