### ISSUE TITLE
DLL runtime issues with API on Windows

### ISSUE THREAD

**Issue by antxv** [tesseract-ocr/tesseract#4161]
### Current Behavior

I am using MSYS2 to install tesseract on Windows, following the [installation instructions](https://tesseract-ocr.github.io/tessdoc/Installation.html):
```
pacman -S mingw-w64-x86_64-tesseract-ocr
pacman -S mingw-w64-x86_64-tesseract-data-eng
```

Then, I am attempting to run [the example code](https://tesseract-ocr.github.io/tessdoc/APIExample.html).

When I run my executable, I get the following pop up error:

```
the procedure entry point _ZSt17_istream_extractRSiPcx could not be located in the dynamic link library C:\msys64\mingw64\bin\libtesseract-5.dll
```

Any thoughts on what is causing this?

### Expected Behavior

No error.

### Suggested Fix

unknown

### tesseract -v

not applicable

### Operating System

Windows 10

### Compiler

g++ (Rev6, Built by MSYS2 project) 12.2.0

**Comment by stweil** [comment]
Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions or report it to MSYS2.

**Comment by stweil** [comment]
It also looks like this is a duplicate of https://github.com/otiai10/gosseract/issues/296.

**Comment by antxv** [comment]
I just updated the other issue, which describes a different problem that is specific to that package. Please reopen that one.

**Comment by antxv** [comment]
Thanks, I will ask on the group. However, considering I followed the simple directions and encountered an error, isn't that an issue?

**Comment by stweil** [comment]
That's an issue, but not one for the Tesseract repositories.

It might be that you have an issue caused by a local mix of incompatible software. Then it's something which you have to solve for yourself.

Or it might be an issue with the software distribution. The developers of Tesseract have no chance to test and track them all. If there were more reports that some documented installation does not work, I'd consider an update of the documentation, but typically not based on a single report.

**Comment by antxv** [comment]
Makes sense. For posterity, I think I discovered the problem: https://groups.google.com/g/tesseract-ocr/c/QGTdZ9lY7Hc
