### ISSUE TITLE
Broken GitHub action msys2-4.1.1

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#4351]
The [GitHub action msys2-4.1.1 currently fails](https://github.com/tesseract-ocr/tesseract/actions/workflows/msys2-4.1.1.yml). The last successful run was in 2023. Is this action still useful? Then a fix is required. Or should it be removed?

**Comment by stweil** [comment]
The action was added in pull request #3356.

**Comment by danpla** [comment]
It looks like this action simply installs the tesseract package from MSYS2 and runs the command line tools with the -v flag. I don't know what the point of this is, but the action definitely fails because MSYS2 no longer provides the tesseract package for i686 (mingw32): https://packages.msys2.org/base/mingw-w64-tesseract-ocr

**Comment by amitdo** [comment]
Fixed in commit d30f45fbfd71de
