### ISSUE TITLE
Add spaces in title of Wiki pages

### ISSUE THREAD

**Issue by zuphilip** [tesseract-ocr/tesseract#486]
I suggest to add spaces in the title of the wiki pages, e.g. the newly created page https://github.com/tesseract-ocr/tesseract/wiki/NeuralNetsInTesseract4.00:

"NeuralNetsInTesseract4.00" --> "Neural Nets In Tesseract 4.00"

The spaces will be changed in the url by dashes i.e. https://github.com/tesseract-ocr/tesseract/wiki/Neural-Nets-In-Tesseract-4.00. This is more conform to the other pages, but there are more wiki pages missing some spaces.

Is this okay?

**Comment by zdenop** [comment]
Please use teseract forums for asking questions... 
Changing urls of old(er) pages is IMO bad idea - it will break links on other pages/projects...

**Comment by zuphilip** [comment]
Uff..., well, then I don't understand the sentence "Please do not change the title of any wiki page without a permission from Tesseract developers." at https://github.com/tesseract-ocr/tesseract/wiki CC @amitdo . I would expect that I can ask permission from developers in an issue at GitHub, if one has to use the user forum for that, then the sentence should be reformulated.

**Comment by zdenop** [comment]
@amitdo: can you please clarify? I think  fresh new wiki page titles could be changed...

**Comment by amitdo** [comment]
Hi @zuphilip :-)

I added it a few hours ago.

Recently, a user change a lot of wiki page titles. The issues I see with doing so are:
* There were many links to some of the wiki pages from Tesseract issues, threads in Tesseract mailing list, blogs posts, etc. The changes broke those links. 
* I contribute to some of those pages, especially to the TrainingTesseract page where I did ton of editing.
With the change of the title the history of the page editing is gone from the wiki interface. It look like I and other who contribute to those pages never did so. Personally, this situation of omitting credits, upset me and piss me off :(

**Comment by stweil** [comment]
> With the change of the title the history of the page editing is gone from the wiki interface. 

That looks like something which could be simply improved by the GitHub people. I get the full history in a local clone of the wiki with `git log --follow Training-Tesseract.md`.

**Comment by Shreeshrii** [comment]
@amitdo

My apologies for the unintended consequences of title changes. I was trying
to make all related pages in wiki come together, eg. Training methofs for
various versions, box files, tesstrain etc. I had no idea that it would
remove page history and previous authors. I also realize that it has led to
broken links.

Is there a way to display broken links in the wiki so that they can be
fixed?

On 22-Nov-2016 3:16 PM, "Amit D." <notifications@github.com> wrote:

Hi @zuphilip <https://github.com/zuphilip> :-)

I added it a few hours ago.

Recently, a user change a lot of wiki page titles. The issues I see with
doing so are:

   - There were many links to some of the wiki pages from Tesseract issues,
   threads in Tesseract mailing list, blogs posts, etc. The changes broke
   those links.
   - I contribute to some of those pages, especially to the
   TrainingTesseract page where I did ton of editing.
   With the change of the title the history of the page editing is gone
   from the wiki interface. It look like I and other who contribute to those
   pages never did so. Personally, this situation of omitting credits, upset
   me and piss me off :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/486#issuecomment-262194003>,
or mute the thread

**Comment by Shreeshrii** [comment]
Stefan,
Is it possible for you to undo the title changes?

**Comment by amitdo** [comment]
Shree @Shreeshrii,

I knew that you are the one that did those titles edits and I was sure you had good intentions. I don't blame you, so please don't feel bad about that :-) 

I blame Github devs.

Stefan @stweil, the fact that I can clone it and see my changes is not helping me.

**Comment by stweil** [comment]
> Is it possible for you to undo the title changes?

I am not sure whether undoing your changes is the right way. Of course the wiki internal links must work, so maybe some links have to be fixed. I would not care for external links. They will still reach the wiki, and people who are interested will be able to find the page they are looking for.

@amitdo, I just contacted GitHub support and suggested to enhance the history, so maybe it will show all contributions (also those before a rename) in the future.

Personally I prefer nice looking titles (that implies spaces between words).

Technically anybody can rename titles, also back to the old ones. It's easier to revert changes in a local wiki clone, but only project owners can push such modifications.

**Comment by zuphilip** [comment]
@amtido et  al. For the newly created pages, I will leave it up to you or any other of the core developer to change the page name.

**Comment by amitdo** [comment]
>@amitdo, I just contacted GitHub support and suggested to enhance the history, so maybe it will show all contributions (also those before a rename) in the future.

Thanks for that, although I'm sceptical about the chance they will do something about this issue. 

I was told that wikipedia's wiki does not have this issue.

With git itself and also with Github interface for code changes the history is preserved.

> I would not care for external links. They will still reach the wiki, and people who are interested will be able to find the page they are looking for.

This is called [breaking the web](https://www.google.co.il/search?client=ubuntu&channel=fs&q=%22breaking+the+web%22+%22broken+links%22) and it's not nice.

Some user re-added the 'deleted' pages with a link to the 'new' pages. In one hand it solves the broken links issue, but on the the other hand it creates a lot of ugly duplicates in the wiki TOC. 

>Personally I prefer nice looking titles (that implies spaces between words).

Personally, I think the fact that the wiki title does not have whitespace is a minor issue, and due to the implications I mentioned earlier, it should not be changed unless...
* It's a new wiki page (with no external links to it)
* The Authors of the page agree with the change.


Some projects block the option to freely do any edits in the wiki content, but I don't suggest to so in this project. More fine-grained permissions control options in the wiki would be very helpful, e.g. options to block title editing and page deletion, an option to 'protected page' - block any editing for certain pages, etc.

**Comment by amitdo** [comment]
Maybe not many people care about this issue as I do...

>@amitdo : For the newly created pages, I will leave it up to you or any other of the core developer to change the page name.

@zuphilip,
@theraysmith or @zdenop should decide about it.

Zdenko, if you don't like my new 'policy' you can remove it from the 'Home' wiki page.

**Comment by stweil** [comment]
> Thanks for that, although I'm sceptical about the chance they will do something about this issue.

Well, at least they have sent an answer:

"This does sounds like it would be a useful addition to wiki revisions. I've passed your request onto the team to consider. I can't promise if or when we would implement but thanks for writing in."

**Comment by amitdo** [comment]
I now see that the previous edits were preserved in the interface of the global history.
https://github.com/tesseract-ocr/tesseract/wiki/_history?page=6
:-)

I now think it OK to change the titles of **new** wiki pages...
@zdenop?

If you change the title of a page don't do changes to the body text in the same edit.


To I changed only the title

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/Improve-Quality/_compare/deccb78%5E...deccb78

This broke some links (Readme, Wiki).

What should we do now?
1) Revert this change?
2) Fix the links?

**Comment by amitdo** [comment]
CC: @andrewda

**Comment by andrewda** [comment]
My bad! Thought it was a typo, will revert until a consensus is made here.

**Comment by andrewda** [comment]
@amitdo Is there an issue with the revert button on the wiki `_compare` page? I clicked "Revert" assuming it would undo the title change and now both pages seem to be gone...

**Comment by amitdo** [comment]
Seems like a bug in GitHub.

https://github.com/contact

**Comment by amitdo** [comment]
The wiki interface considers a change of a wiki page title as creating a **new page**.
So the wiki reverted your last change - and deleted this page.
Unfortunately, the story ends here...

The wiki can be cloned and the page should still be accessible in the history. It can be recovered.

**Comment by andrewda** [comment]
Ah, I understand now. Had no idea that's how GitHub renamed pages, very sorry for the trouble.

**Comment by amitdo** [comment]
The source of the problem is git itself. The wiki is built on top of it.

**Comment by amitdo** [comment]
The page was somehow restored.
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality
