### ISSUE TITLE
Don't utilize Leptonica debug parameters or functions

### ISSUE THREAD

**Issue by jbreiden** [tesseract-ocr/tesseract#557]
@theraysmith 

These two Leptonica calls have optional debugging parameters.

pixGenerateHalftoneMask
pixGenHalftoneMask

They are found in imagefind.cpp in code and comments, to support an optional
parameter called textord_tabfind_show_images

https://github.com/tesseract-ocr/tesseract/blob/master/textord/imagefind.cpp#L86

In general, the debug paths in Leptonica are not great from security perspective
and setting that debug parameter to null or false is recommended. If possible
I encourage removing the the textord_tabfind_show_images feature entirely.

In addition, there is significant use of pixDisplayWrite for debugging purposes.
This is deprecated and also a security headache, and I encourage removing
all calls to this function.

It is possible that this list is not exhaustive but it probably is. The rule of thumb 
is try to avoid debug-specific Leptonica code paths wherever possible in release builds.

**Comment by DanBloomberg** [comment]
I am fairly sure that pixGenHalftoneMask() (and the wrapper pixGenerateHalftoneMask()) are the only leptonica functions in tesseract that have a debug argument.

It should be OK in the new tesseract (4.00) to use pixGenerateHalftoneMask() with NULL for the debug pixa.  It would also be nice at the same time for the debug calls to the deprecated functions pixDisplayWrite() and pixDisplayWriteFormat() were removed, because there is no reason that tesseract needs to generate these debug images.

**Comment by DanBloomberg** [comment]
I believe that Ray is removing all use of temp files due to pixDisplayWrite() in tesseract.

**Comment by theraysmith** [comment]
Fixed in commit a1c22fb.
