### ISSUE TITLE
[LSTM] psm 5 produces really bad results (japanese)

### ISSUE THREAD

**Issue by DarkDefender** [tesseract-ocr/tesseract#627]
I've compiled and installed the master branch today and started to play around a bit with text extraction from japanese text. With the supplied training data LSTM seems to be a bit better at horizontal text than the old (oem 0) method.

However, with vertical text LSTM is really bad and does not produce any good results.

This is my results with the following three test images. (I have scaled them to 300 dpi)

[test1](https://cloud.githubusercontent.com/assets/312503/21546356/81151560-cdde-11e6-902c-c2e2cfaed90b.png)
`tesseract test1.png out -l jpn --oem 0 --psm 5 && cat out.txt`
そのかわり・・・・・・
`tesseract test1.png out -l jpn --oem 1 --psm 5 && cat out.txt`
ご 人 心 ‥.

For test2.png, I cut off the top row of a vertical text segment 
[test2](https://cloud.githubusercontent.com/assets/312503/21546355/8114c2c2-cdde-11e6-9f66-5e1e3c3584ee.png)
`tesseract test2.png out -l jpn --oem 0 --psm 5 && cat out.txt`
だ
洗
お
で
`tesseract test2.png out -l jpn --oem 1 --psm 5 && cat out.txt`
ぢ
於
+
レ
`tesseract test2.png out -l jpn --oem 0 --psm 6 && cat out.txt`
でお洗だ“
`tesseract test2.png out -l jpn --oem 1 --psm 6 && cat out.txt`
で お 洗 だ

[test3](https://cloud.githubusercontent.com/assets/312503/21546353/810209a2-cdde-11e6-9ecd-c4f2eb6308c4.png)
`tesseract test3.png out -l jpn --oem 0 --psm 5 && cat out.txt`
心配ご無用
秘密にしますよ
`tesseract test3.png out -l jpn --oem 1 --psm 5 && cat out.txt`
つ 圖 月 庸 明
惟 僕 り せつ 44 ふ 6

Using psm 6 on test3 does make LSTM a bit better, but as with oem 0, it fails to extract the text correctly...

`tesseract test3.png out -l jpn --oem 0 --psm 6 && cat out.txt`
秘心
壽醒
し無
ま用
す
よ
`tesseract test3.png out -l jpn --oem 1 --psm 6 && cat out.txt`
秘 心
は :
し 無
ま 用
す
ボ

I've also noticed that even if LSTM is a bit better with horizontal text, it seems to print out the result with spaces even if there are no space in the original text. For example:
はははは
Becomes:
は は は は

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/NeuralNetsInTesseract4.00#integration-with-tesseract

>The neural network engine has not yet been integrated to enable the multi- language mode that worked with Tesseract 3.04, but this will be improved in a future release. Vertical text is also not yet supported, so support for Japanese and Traditional Chinese for example are limited to horizontally rendered text.

**Comment by jbreiden** [comment]
Vertical Japanese is not yet trained on LSTM.

On Dec 29, 2016 7:09 AM, "DarkDefender" <notifications@github.com> wrote:

I've compiled and installed the master branch today and started to play
around a bit with text extraction from japanese text. With the supplied
training data LSTM seems to be a bit better at horizontal text than the old
(oem 0) method.

However, with vertical text LSTM is really bad and does not produce any
good results.

This is my results with the following three test images. (I have scaled
them to 300 dpi)

test1
<https://cloud.githubusercontent.com/assets/312503/21546356/81151560-cdde-11e6-902c-c2e2cfaed90b.png>
tesseract test1.png out -l jpn --oem 0 --psm 5 && cat out.txt
そのかわり・・・・・・
tesseract test1.png out -l jpn --oem 1 --psm 5 && cat out.txt
ご 人 心 ‥.

For test2.png, I cut of the top row of a vertical text segment
test2
<https://cloud.githubusercontent.com/assets/312503/21546355/8114c2c2-cdde-11e6-9f66-5e1e3c3584ee.png>
tesseract test2.png out -l jpn --oem 0 --psm 5 && cat out.txt
だ
洗
お
で
tesseract test2.png out -l jpn --oem 1 --psm 5 && cat out.txt
ぢ
於
+
レ
tesseract test2.png out -l jpn --oem 0 --psm 6 && cat out.txt
でお洗だ“
tesseract test2.png out -l jpn --oem 1 --psm 6 && cat out.txt
で お 洗 だ

test3
<https://cloud.githubusercontent.com/assets/312503/21546353/810209a2-cdde-11e6-9ecd-c4f2eb6308c4.png>
tesseract test3.png out -l jpn --oem 0 --psm 5 && cat out.txt
心配ご無用
秘密にしますよ
tesseract test3.png out -l jpn --oem 1 --psm 5 && cat out.txt
つ 圖 月 庸 明
惟 僕 り せつ 44 ふ 6

Using psm 6 on test3 does make LSTM a bit better, but as with oem 0, it
fails to extract the text correctly...

tesseract test3.png out -l jpn --oem 0 --psm 6 && cat out.txt
秘心
壽醒
し無
ま用
す
よ
tesseract test3.png out -l jpn --oem 1 --psm 6 && cat out.txt
秘 心
は :
し 無
ま 用
す
ボ

I've also noticed that even if LSTM is a bit better with horizontal text,
it seems to print out the result with spaces even if there are no space in
the original text. For example:
はははは
Becomes:
は は は は

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tesseract-ocr/tesseract/issues/627>, or mute the thread

**Comment by DarkDefender** [comment]
@amitdo @jbreiden Ah, I missed that wiki page, sorry. Should I close this issue or keep it open until this is implemented?

**Comment by amitdo** [comment]
I think you can keep it open. An admin can close it if he wants to.

**Comment by amitdo** [comment]
Ray added jpn_vert.traineddata
https://github.com/tesseract-ocr/tessdata/tree/master/best

**Comment by DarkDefender** [comment]
@amitdo Thanks for the headsup! It seems to work better than the old (oem 0) method for me.

**Comment by amitdo** [comment]
@zdenop, please close this issue.
