### ISSUE TITLE
What is the official source for training data?

### ISSUE THREAD

**Issue by tom111** [tesseract-ocr/tesseract#70]
Hi,
I'm packaging tesseract for Gentoo Linux. What is the up-to-date download location for training data? We used to download from Google Code, but that looks like it is going to close eventually. Ideally we would like to have pre-packaged .tar.gz files for each language (like we used to have on Google code). Would that be possible also on github?

Should we still use the language files from [here](https://code.google.com/p/tesseract-ocr/downloads/list) with 3.04.00 ?

Thanks!

**Comment by zdenop** [comment]
Use tesseract forums for asking support[1]
[1] https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice

**Comment by jimregan** [comment]
Having tarballs is certainly possible, but I don't really see the point for most languages, which would only contain a single file. It does make sense for the languages that use Cube (that is, the trained data consists of a number of files), but there has been some kind of problem with that (I don't know the details), and Cube is expected to go away some time in the future.
As a sidenote, it would have been helpful if you could have made it clear that the issue was, in fact, an issue, by phrasing it as such: "tarballs not provided for traineddata" is an issue; "what is the official source...?" is a support question.

**Comment by tom111** [comment]
I'm not a user of tesseract user, I'm packaging it. Therefore I'm looking to quickly identify which files I need to provide to the users.  At the moment it seems to be the case that I have to get the source from github, and language files from an old version of google code.  So one issue is that it's not documented that the 3.02 language files and tesseract-3.04 belong together. From what I read in the forums this is indeed the case. The issue is NOT that I want you to tar individual files. The issue is that there is no single official location where to download everything needed to ship your software to your users (in Gentoo).

**Comment by zdenop** [comment]
1. There is an official location for download everything: repository tessdata[1]. Just to point out - you need package at-least eng and osd. Maybe have a look how debian packaged it or cygwin[2].

2. Ray asked[3] for suggestion regarding shipping/packaging problem - so this is IMO right place to discuss possible issues (also in past there was some suggestions who to distribute language files).

[1] https://github.com/tesseract-ocr/tessdata
[2] https://groups.google.com/d/msg/tesseract-ocr/dqT_KjKq0BM/PUMvC7DmIwAJ
[3] https://groups.google.com/d/msg/tesseract-dev/8e0F2cK2YzU/izie4Ysx-HEJ

**Comment by tom111** [comment]
OK, thanks. Tesseract-3.04.00 is in Gentoo with up to date traineddata now.
