### ISSUE TITLE
libtiff underlinking in 3.0x.y

### ISSUE THREAD

**Issue by mkszuba** [tesseract-ocr/tesseract#739]
Hello,

Tesseract-3.04.01 (and having briefly glanced at the code, likely so does 3.05.00) does not explicitly link libtesseract against libtiff even when the former references symbols from the latter. This results in the following error when one attempts to build tesseract using a linker that dislikes implicit linking, e.g. gold:

/bin/sh ../libtool  --tag=CXX   --mode=link x86_64-pc-linux-gnu-g++  -O2 -pipe -march=native -std=c++11 -lOpenCL -Wl,-O1 -Wl,--as-needed -Wl,--as-needed -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -O2 -pipe -march=native -o tesseract tesseract-tesseractmain.o libtesseract.la   -lrt -llept -lpthread 
libtool: link: x86_64-pc-linux-gnu-g++ -O2 -pipe -march=native -std=c++11 -Wl,-O1 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -O2 -pipe -march=native -o .libs/tesseract tesseract-tesseractmain.o  -lOpenCL -Wl,--as-needed ./.libs/libtesseract.so -lrt -llept -lpthread
./.libs/libtesseract.so: error: undefined reference to 'TIFFFdOpen'
./.libs/libtesseract.so: error: undefined reference to 'TIFFGetFieldDefaulted'
./.libs/libtesseract.so: error: undefined reference to 'TIFFGetField'
./.libs/libtesseract.so: error: undefined reference to 'TIFFScanlineSize'
./.libs/libtesseract.so: error: undefined reference to 'TIFFReadRGBAImageOriented'
./.libs/libtesseract.so: error: undefined reference to 'TIFFReadScanline'
./.libs/libtesseract.so: error: undefined reference to 'TIFFClientOpen'
./.libs/libtesseract.so: error: undefined reference to 'TIFFReadDirectory'
./.libs/libtesseract.so: error: undefined reference to 'TIFFCleanup'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:591: tesseract] Error 1
make[2]: Leaving directory '/tmp/tesseract-3.04.01/api'
make[1]: *** [Makefile:480: all-recursive] Error 1
make[1]: Leaving directory '/tmp/tesseract-3.04.01'
make: *** [Makefile:389: all] Error 2

Manually adding -ltiff to the list of libraries in api/Makefile allows tesseract to build successfully, then again it is not a proper solution because e.g. the pkg-config file it installs still doesn't list that library.

**Comment by idiosyncraticee** [comment]
Can you be more specific on how to manually add -ltiff to api/Makefile?  I'm running MacOS Sierra 10.12.3 and getting an error about linking the ltiff when compiling the 4.0 alpha version.

libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o -Wl,-bind_at_load  -L/usr/local/Cellar/icu4c/56.1/lib ./.libs/libtesseract.dylib -L/usr/local/Cellar/leptonica/1.74.1/lib -llept -ltiff
ld: library not found for -ltiff
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tesseract] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by Shreeshrii** [comment]
You may need to install libtiff. try the following (or equivalent command
for your os) before building tesseract

sudo apt-get install libtiff5-dev


ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by idiosyncraticee** [comment]
Thank you so much Shreeshrii!  That tip got me pointed in the right direction.  For anybody else that stumbles up this here is the config command that worked.  The second library path contains the libtiff libraries.

./configure CC=gcc CXX=g++ CPPFLAGS=-I/usr/local/Cellar/icu4c/56.1/include LDFLAGS="-L/usr/local/Cellar/icu4c/56.1/lib -L/usr/local/lib"

**Comment by mkszuba** [comment]
@idiosyncraticee  Glad you have solved your problem but for the record, that was completely unrelated to the issue at hand. Indeed, the command-line snippet you have posted suggests that libtiff underlinking has been fixed in the 4.0 branch - one can clearly see -ltiff there.

**Comment by jbreiden** [comment]
Tesseract does not reference any libtiff symbols. I don't understand this at all.

$ find  | xargs grep TiffFdOpen

**Comment by amitdo** [comment]
>Tesseract does not reference any libtiff symbols

You might want to read [opencl/openclwrapper.cpp](https://github.com/tesseract-ocr/tesseract/blob/3.05/opencl/openclwrapper.h) ...

**Comment by jbreiden** [comment]
Thanks @amitdo, I stand corrected. All that code is currently unused but you are correct, it is right there.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/commit/9ec0c4fa9c983

This one was not backported to 3.05.

**Comment by RandomDSdevel** [comment]
Per [an issue](https://github.com/Homebrew/homebrew-core/issues/10380) I reported downstream to maintainers of [the macOS Homebrew package manager](https://github.com/Homebrew/brew)'s [Core tap](https://github.com/Homebrew/homebrew-core) (and as specifically pointed out by [this comment](https://github.com/Homebrew/homebrew-core/issues/10380#issuecomment-283186646) on it,) this issue also occurs under OS X/macOS 'El Capitan' v10.11.6.  As Homebrew's maintainers prefer to use only patches available upstream, can the priority of this issue's resolution be bumped up just a tad, please?

**Comment by Shreeshrii** [comment]
> 9ec0c4f

> This one was not backported to 3.05.

>>  All that code is currently unused but you are correct, it is right there.

@egorpugin @zdenop  Should it be added to the 3.05 for the timebeing i.e. till opencl is looked at.

**Comment by amitdo** [comment]
@jbreiden
>I stand corrected. All that code is currently unused but you are correct, it is right there.

Not exactly...
https://github.com/tesseract-ocr/tesseract/blob/40dc28026b61/api/baseapi.cpp#L1038

```
#ifdef USE_OPENCL
    if ( od.selectedDeviceIsOpenCL() ) {
      pix = (data) ?
          od.pixReadMemTiffCl(data, size, page) :
          od.pixReadTiffCl(filename, page);
    } else {
```

This issue is about 3.05. Should we remove the calls to these two functions in 3.05 as you have done in 4.00?

**Comment by egorpugin** [comment]
In general I think we may push needed changes to 3.05 branch and tag patch releases (3.05.01, 3.05.02, ...).

**Comment by Shreeshrii** [comment]
Looks like @zdenop is busy. Is he the only one who can push these changes and tag patch releases?

**Comment by zdenop** [comment]
PR is welcomed.
BTW: At this stage of support of OpenCL I suggest to remove OpenCL from 3.05 and 4.0x

**Comment by RandomDSdevel** [comment]
@mkszuba, @idiosyncraticee, @Shreeshrii, @jbreiden, @amitdo, @egorpugin, @zdenop:  If you don't mind my trying my hand at resolving this issue, what's the local procedure for submitting backport PRs, at least with respect to the Git/GitHub workflow?

**Comment by stweil** [comment]
> BTW: At this stage of support of OpenCL I suggest to remove OpenCL from 3.05 and 4.0x

OpenCL worked for me (after I had spent some time on it and contributed several pull requests) at least until end of last year, both with 3.05 and with 4.0x. Depending on the graphic card, it can be a great gain. That is relevant for some OCR projects which would take years on a single CPU.

A test which I just have done with latest Tesseract code was not successful, but I estimate that it can be fixed again.

**Comment by RandomDSdevel** [comment]
@mkszuba, @idiosyncraticee, @Shreeshrii, @jbreiden, @amitdo, @egorpugin, and/or @zdenop:  
> @mkszuba, @idiosyncraticee, @Shreeshrii, @jbreiden, @amitdo, @egorpugin, and/or @zdenop:  If you don't mind my trying my hand at resolving this issue, what's the local procedure for submitting backport PRs, at least with respect to the Git/GitHub workflow?  Do I just have to mention the commit from which the new one backports changes, or will I have to do something more complicated (like, say, use `git cherry-pick` or something…?)  

…or would one of you guys rather handle this yourselves since you're more familiar with the codebase than I am?  Like I hinted at [earlier](https://github.com/tesseract-ocr/tesseract/issues/739#issuecomment-283486022) in this thread, I'm just bumbling around trying to fix an [issue](https://github.com/Homebrew/homebrew-core/issues/10380) downstream in [Homebrew](https://github.com/Homebrew/brew)'s [Core tap](https://github.com/Homebrew/homebrew-core) that I referenced back then.

**Comment by stweil** [comment]
@RandomDSdevel, I don't think that you need this fix to get 3.05 running with Homebrew. The error message caused by the missing `libtoolize` on macOS is confusing, but it's only a cosmetic problem. And if you don't use OpenCL (`--enable-opencl`), building Tesseract should work. There are good reasons why OpenCL is disabled by default.

**Comment by RandomDSdevel** [comment]
@stweil:  I already got the `libtoolize` issue fixed here upstream in #750, but that has turned out to be _completely_ orthogonal to this one and is also just coincidentally waiting for said fix to be backported (from `master`, in its case.)  As for OpenCL, that's _actually_ what I've been wanting to get working _all along!_  I believe my rationale for efforts in this space agrees, at least at some level, with the sentiment you expressed earlier:  

> Depending on the graphic card, it [(OpenCL)] can be a great gain. That is relevant for some OCR projects which would take years on a single CPU.

As such, I'll be ready to propagate the backport of [`9ec0c4f`](https://github.com/tesseract-ocr/tesseract/commit/9ec0c4fa9c983) from 4.0.x to 3.0.5 postulated [earlier](https://github.com/tesseract-ocr/tesseract/issues/739#issuecomment-283117301) as the only change needed to resolve this issue here upstream to Homebrew as a downstream mirror of an official upstream patch if a new version of Tesseract is not tagged.  If a new version of Tesseract _is_ tagged, then I would be perfectly happy with propagating _that_ downstream to Homebrew instead of the patches containing the resolutions for this issue and, simultaneously but, again, orthogonally, #750.  Either way, all I currently wish to do is get Tesseract to build with `--enable-opencl` set by Homebrew (via the `--with-opencl` option to its build formula for Tesseract) _independent_ of any further reworking of Tesseract's OpenCL support, such as that suggested by [_this_ comment](https://github.com/tesseract-ocr/tesseract/issues/739#issuecomment-283608563), that is undertaken in the future.  The intermediate resolution of #750 was, for me, just a nice little side bonus in the meantime.

**Comment by zdenop** [comment]
1. In case of OpenCL, "-ltiff" is added automatically by [configure](https://github.com/tesseract-ocr/tesseract/blob/3.05/configure.ac#L81). So there is no need to add linking to libtiff because of OpenCL (if yes then there is other problem that should be fixed!)
2. I just checked compilation of 3.05 on openSUSE linux and it works without problem/modification. Linking to libtiff is done "automatically" (based on leptonica?): 
```
libtool: link: ranlib .libs/libtesseract_api.a
libtool: link: ( cd ".libs" && rm -f "libtesseract_api.la" && ln -s "../libtesseract_api.la" "libtesseract_api.la" )
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11 -version-info 3:5 -no-undefined   -o libtesseract.la -rpath /usr/lib64  libtesseract_api.la ../ccmain/libtesseract_main.la ../textord/libtesseract_textord.la ../wordrec/libtesseract_wordrec.la ../classify/libtesseract_classify.la ../dict/libtesseract_dict.la ../ccstruct/libtesseract_ccstruct.la ../cutil/libtesseract_cutil.la ../viewer/libtesseract_viewer.la ../ccutil/libtesseract_ccutil.la ../opencl/libtesseract_opencl.la ../cube/libtesseract_cube.la ../neural_networks/runtime/libtesseract_neural.la -llept -lpthread 
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/crti.o /usr/lib64/gcc/x86_64-suse-linux/4.8/crtbeginS.o  -Wl,--whole-archive ./.libs/libtesseract_api.a ../ccmain/.libs/libtesseract_main.a ../textord/.libs/libtesseract_textord.a ../wordrec/.libs/libtesseract_wordrec.a ../classify/.libs/libtesseract_classify.a ../dict/.libs/libtesseract_dict.a ../ccstruct/.libs/libtesseract_ccstruct.a ../cutil/.libs/libtesseract_cutil.a ../viewer/.libs/libtesseract_viewer.a ../ccutil/.libs/libtesseract_ccutil.a ../opencl/.libs/libtesseract_opencl.a ../cube/.libs/libtesseract_cube.a ../neural_networks/runtime/.libs/libtesseract_neural.a -Wl,--no-whole-archive  -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/lib64 /usr/lib64/liblept.so -lz -lpng -ljpeg -lgif -ltiff -lwebp -lopenjp2 -lpthread -L/usr/lib64/gcc/x86_64-suse-linux/4.8 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/lib -L/usr/lib64/gcc/x86_64-suse-linux/4.8/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib64/gcc/x86_64-suse-linux/4.8/crtendS.o /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/crtn.o  -O2   -Wl,-soname -Wl,libtesseract.so.3 -o .libs/libtesseract.so.3.0.5
```
So I guess there should be some other problem...

**Comment by zdenop** [comment]
@mkszuba: Did you compile leptonica with libtiff support?

**Comment by mkszuba** [comment]
@zdenop Turns out my glance at the code was not accurate and the problem has indeed been 3.05.00. My bad, sorry,

**Comment by RandomDSdevel** [comment]
@mkszuba:  Did the fix involve linking Tesseract with a copy of Leptonica linked with libtiff?

**Comment by RandomDSdevel** [comment]
OK, so I communicated with @mkszuba via private e-mail to see if he would be willing to answer my previous comment, but he's looked at my downstream issue, and he has the impression that it's different enough from his that I should probably open a new one here upstream, so I think I'm going to do that if troubleshooting Homebrew/homebrew-core#10380 by trying to build Tesseract under Homebrew fails again (I suspect it will if the problem I'm having is distinct from the one addressed by this issue's preemptive resolution, but maybe I'll get lucky…)

**Comment by RandomDSdevel** [comment]
Aaaaannnd…the build failed again, so the issue is as reproducible on my machine under Homebrew as I thought.  I'd better fork my issue off into a new one and stop derailing this one, then, because I'm starting to believe @mkszuba that it's not the same…

**Comment by RandomDSdevel** [comment]
Per the GitHub issue mention notification above, I've now opened #786 to pursue Homebrew/homebrew-core#10380 further here upstream.
