### ISSUE TITLE
Training tesseract to recognize text from images

### ISSUE THREAD

**Issue by smac89** [tesseract-ocr/tesseract#82]
Is there a way to train tesseract to recognize a limited amount of text from an image. I am making a small app that recognizes a printed list of topics and so far using the tess-two library, tesseract does not fully recognize any of the text in the image. I am quite new to OCR so I'm not sure how to make this work. So far all the training instructions I've seen require a font file which I don't have. All I have are different images of the printed text.

How do I train tesseract to recognize the text from that? Where do I start?

**Comment by chrys87** [comment]
Hi,
for me it helps often to upscale a image.
in ocrdesktop i resize the image by factor 3 (Bicubic). This brings quite good results.
Cheers

**Comment by Wikinaut** [comment]
In case that you use screenshots, please notice, that screenshots usually have 72dpi, which is not sufficient for Tesseract. I admit, that this is not so well know, however, it is mentioned since a long time here https://code.google.com/p/tesseract-ocr/wiki/FAQ#Is_there_a_Minimum_Text_Size?_%28It_won%27t_read_screen_text!%29

> Is there a Minimum Text Size? (It won't read screen text!)

> There is a minimum text size for reasonable accuracy. You have to consider resolution as well as point size. Accuracy drops off below 10pt x 300dpi, rapidly below 8pt x 300dpi. A quick check is to count the pixels of the x-height of your characters. (X-height is the height of the lower case x.) At 10pt x 300dpi x-heights are typically about 20 pixels, although this can vary dramatically from font to font. Below an x-height of 10 pixels, you have very little chance of accurate results, and below about 8 pixels, most of the text will be "noise removed". 


I recommend:

* remember never to use JPEG (because this is a lossy compresison format) when saving images with text (use: PNG, or use TIF, or GIF as the last choice)
* resize your screenshots or images to at east 300dpi, or 400dpi
* read http://bertanguven.com/faster-conversions-from-pdf-to-pngjpeg-imagemagick-vs-ghostscript/
```
density=400
gs -dNOPAUSE -sDEVICE=png16m -sOutputFile=$image -r$density -q $file -c quit
```

**Comment by amitdo** [comment]
@Wikinaut, why do you link to the old wiki at googlecodei instead to the new one at github?
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#is-there-a-minimum-text-size-it-wont-read-screen-text
Here is another useful wiki page?
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality

**Comment by Wikinaut** [comment]
I update my posting above accordingly. Thanks

**Comment by zdenop** [comment]
Please use tesseract user forum for support[1]. Also do not forget to search forum for you topic before asking for help.
[1] https://github.com/tesseract-ocr/tesseract/wiki/FAQ#rules-and-advice

**Comment by suraj990** [comment]
open
    raise ValueError("bad mode %r" % mode)
ValueError: bad mode 'sign.png' 

what to do i am helpless
