### ISSUE TITLE
Error sequence in persian language

### ISSUE THREAD

**Issue by Nigje** [tesseract-ocr/tesseract#894]
when i use tesseract with -l fas some time i get sequence error like follow:
 = ڤکڵ۱۴ـ۵ـکوقەگ|حهدسـ٥درمحموشۀكاحمورهپـوران ف
for this image
![20170506_133142](https://cloud.githubusercontent.com/assets/10100596/25782692/f4c2dfc4-3364-11e7-861a-f3da05d37dc3.jpg)

also this error occur in arabic language
how can i change configs or tessconfig to fix this bug?

**Comment by ibr123** [comment]
Hi,

what is the version of the tesseract and leptonica that you have used? 
i made detection on the image that you have shared and got the following results (disregard the numbers):
شکل کوشک احمد شاه در مجموعۀ کاخ موزۀ نیاوران
although the training was on the Arabic files not Farsi

**Comment by Nigje** [comment]
orginal image:
![20170506_133142](https://cloud.githubusercontent.com/assets/10100596/25798783/c20f7ae0-33f7-11e7-978b-dd47a6c98b06.jpg)

please test this image.

**Comment by ibr123** [comment]
@Nigje 

this is the results

عکسهای دورۀ قاجار /
/ آثار نقاشی هنرمندان ایرانی
_ __ هنرهای .. .
__ مینیاتور و آثار خنرهای سنتی _

_ © © © روشهای تولید برف
_ سیر خطوط در ایران __
نقاشی و مینیاتور استاد فرشجیان

قالی، نقاشی، خط و آثار دورههای

ا ا

0 آثار باستانی و هنرهای تیوی ر ز
آثار دورۀ قاجار و پهلوی و هدایای بعضی کشورها .
_ تفاشی های دودۀ فاجار ر .

_ اشیا و تایلوهای اروپایی هدیه شده به دربار قاجار _
/ عکسهای دورۀ قاجار 5

آثار دورۀ پهلوی

 

هنری، تخصصی

" انواع گوناگون گل و گیاه

 

 

شکل کوشک احمد شاه در مجموعۀ کاخ موزۀ نیاوران

as you can see the detection is quite good but the problem is that, the column on the right wasn't detected, but the column on the right was detected, also the text below the house is detected as well

**Comment by Nigje** [comment]
I build tesseract with vs2015 and use api.

for build tesseract also i have built 
leptonica-1.74.1  [MSC v.1900 LIB Debug x64]
 libgif 4.1.6(?) 
 libjpeg 9a 
 libpng 1.6.29 
 libtiff 4.0.7 
 zlib 1.2.

i don't known what is problem !!?

**Comment by roozgar** [comment]
​do you get any error?​

**Comment by Shreeshrii** [comment]
Default setting of page segmentation treats the image as columns of text. If you want the whole line recognized as a unit, try with --psm 6.

The Eastern Arabic numerals are currently not recognized, it is a known issue - https://github.com/tesseract-ocr/langdata/issues/72

**Comment by amitdo** [comment]
Default PSM values:
API - 6
Command line - 3

**Comment by ibr123** [comment]
@roozgar i got an error but i think its due to the picture itself, the message was: "image too small to scale"
not a detection error i think

i tired the detection one more time with the argument psm , seems both columns were detected, the accuracy seems good, since I'm detecting against Arabic lstmf files with fas.traineddata, but i got to ask, if what is the typical order for detecting a table, is it each row is been detected as a line?

@Shreeshrii i know about this issue, actually i was the one who mentioned that problem at the first place :)

**Comment by ibr123** [comment]
@Nigje 

here are the new results, the full command was: tesseract farsi2.jpg results_farsi -l fas ./tessdata-dir ./tessdata  --oem 1  --psm 6

١
2 .
سران ل: ش ۰
ن عکس خانه عکس های دورۀ قاجار
س ار ن ٣8 ه ی | ن ر __ _ عاکكس نیا فوفۀ ا چا ر ی ا
8 هنرهای زیبا آثار نقاشی هنرمندان ایرانی ۱
سست 55555 نت. 05555
۲۶ __ خترهای بهای _ |. جت 7 - هنرهای تج بیار تی بوت ی س بت تی ت بی __
۲۷۲ . = اج پ س __ وارون هاو خر ر ر سس
۸ صنعت برق روشهای تولید برق .
سری سوت پ 7-72 دا خر صد سست س می ی س ۳۷ / 2 خ % ب- 7 ۷۰۰ [
| ۹ { میرعماد . | سیر خطوط در ایران
ست خس خ پ پیت پی تب رت رپ ت [ 5 5 سستی س . . س سست کر سات جت جم
ا ا نقاشی ومینیاتوراساد فرشچیان ا
و صاحبقرانیه قالی، نقاشی، خط و آثار دورههای
ا پهلوی وصفوی ا
۲ __ جهاننما _ ر ا. آثارباستانی و هنرهای تجسمی ر م ست |
۳ __ کاج احمدشاهی س ایر _ __ آر دورۀ فاجار و پهلوی و جدای نی کر ی |
۴ ! نگارخانه ١ نقاشیهای دورۀ قاجار 2
سس وت م و ٦٣٣٣ پپت ٣٣-00005005 آبا ت ک ب چ ت پیس ک پس ۰ سیب ا تست ی ی ب حی
۵ __ حخوضفانه __ اشیا و تابلوهای اروپایی هدیه شده به دربار آقا جار .
۳۶ | عکس خاند ت
س ر ا ری ر ر را ا _ - . س _ ت 7 را . سست . س ب ه ی ر صص
| س گی س ت ت س ب دس بی ا. ی ن ا یخ گی ی فا ر [
۸ | کاخ ملت آثار دورة بهار بی ١
شیک 5555___ 00055 ۱0055 س __ لوی تخصصی ا ا ا ی
١ ] ۴۰۰ [__ گیاهان داروی سنتی ا انواع گل و کبد ا
۱ 3 ۰و ات . ۰ % . ک ایا %
. ی ن کت حصر ا
شکل کوشک احمد شاه در مجموعۀ کاخ موزۀ نیاوران
۲

**Comment by ibr123** [comment]
@Nigje 
i never used the tesseract api on vs, i use the tesseract engine, the tesseract version that im using is tesseract 4.00alpha with leptonica 1.74.1, and its not possible for any version prior to 4.00alpha to detect Arabic, or Farsi or Urdu, as the new engine contains lstmf files which you can use on detection by adding the argument --oem 1

**Comment by Nigje** [comment]
@ibr123 @roozgar @Shreeshrii @amitdo 
tanks for your comments, problem  resolved.

> tesseract.exe test.png test -l fas --oem 1 --psm 6

 --oem 1 forced tesseract to use only Lstm.

**Comment by Shreeshrii** [comment]
@zdenop Issue Resolved. Please close.

**Comment by netwons** [comment]
my code
```
#!/bin/python3.8
import cv2 
import pytesseract

img = cv2.imread('/home/netwons/Desktop/fff.jpeg')

# Adding custom options
custom_config = r'--oem 3 --psm 6'
text=pytesseract.image_to_string(img,lang="fas", config=custom_config)


f= open("/home/netwons/Desktop/py.txt","w")
f.write(text)
f.close()
```
**but all numbers not show**
