### ISSUE TITLE
opencl/Makefile.am

### ISSUE THREAD

**Issue by amitdo** [tesseract-ocr/tesseract#924]
`AM_CPPFLAGS += ... $(OPENCL_CFLAGS)`

@jbarlow83, @stweil, from where it gets `$(OPENCL_CFLAGS)`?

**Comment by stweil** [comment]
That macro is not set, so it is empty (unless someone sets a value when calling make).

Normally, a `PKG_CHECK_MODULES` test for OpenCL in `configure.ac` would set the macro, but the current implementation does not use `PKG_CHECK_MODULES` for OpenCL.

In most cases the build works even with the wrong macro (that's why I never noticed it).
