### ISSUE TITLE
Feature Request Screenshot Mode

### ISSUE THREAD

**Issue by jsl303** [tesseract-ocr/tesseract#929]
Reading the forum, it seems a lot of people would benefit from having a screenshot mode where Tesseract would automatically process the image to increase the accuracy. I.E. enlarging image, making into black and white, and so on.
Is it possible to implement such feature?
Thanks!

**Comment by Shreeshrii** [comment]
I agree that this would be a useful feature. Specially since tesseract already detects when the image has a low dpi.

Example Image where this would help - https://github.com/tesseract-ocr/tesseract/issues/997

**Comment by Shreeshrii** [comment]
Another related addition could be allowing pdf input. leptonica can be used for converting pdf to multipage tiff - it could be controlled via a config if needed.

https://github.com/DanBloomberg/leptonica/blob/master/prog/pdf2mtiff

Also,  leptonica functions could be used for converting images to 300 dpi / larger size within tesseract itself, which will improve results for a lot of users. Again, it could be implemented via a config, so that those  who prefer to pre-process by themselves for better control can do so.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/blob/master/prog/pdf2mtiff

It's just a bash script that calls ghostscript.

Users can call invoke it directly.

**Comment by AntonKrug** [comment]
VietOCR has this mode already and improves the quality significantly, sometimes sharpening the image helps as well. If not adding this feature at least the "golden" standard what to do with screenshot to make it work with tesseract would be helpful. 

I'm just guessing upscaling by 312.5% to get from 96dpi to 300dpi of windows screenshots, then I do sharpening and then putting it to grayscale. Is there something I shouldn't do? Or something I'm missing? If there is no screenshot feature, at least tell us what we should do in the scripts imagemagick . You have guidelines for scanned text, rotate, remove noise, remove borders etc... Give us at least something which is focused for screenshots.

**Comment by zdenop** [comment]
Tesseract is OCR engine. For image prepossessing you should use external tools.
