### ISSUE TITLE
Error: Illegal min or max specification! "Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75

### ISSUE THREAD

**Issue by oelleo** [tesseract-ocr/tesseract#94]
I run into this error under debian7 (and 8)  with Tesseract 3.03 and also with 3.04.

The solution I found to avoid this is to set the locale LC_NUMERIC to C instead of my locale "fr_FR.UTF-8"

Is there a patch or a new version planned to solve this whitout the need to change my locale ?
Thank you

**Comment by zdenop** [comment]
Did it happen with google traineddata file (or custom training)?

**Comment by oelleo** [comment]
It happened with custom training

**Comment by zdenop** [comment]
Try to set  LC_NUMERIC to C during training

**Comment by oelleo** [comment]
Hello, 
I found that tesseract had a patch for this problem (https://code.google.com/p/tesseract-ocr/issues/detail?id=910)
Why is this not in the new version of Tesseract 3.04 ?
Will it be in the next version ?
Thanks

**Comment by oelleo** [comment]
Btw the custom training I use is not mine so I cannot run it again with LC_NUMERIC=C

**Comment by zdenop** [comment]
Why do you think this patch is not in current version??? issue 910 you are reffering has problem with official google traineddata file. This was fixed.
AFAIR problem is in custom training.

**Comment by oelleo** [comment]
Ok my bad.
But I just tried with the eng.traineddata from official google traineddata file and I've got the same error
"Error: Illegal min or max specification!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75"

**Comment by tfmorris** [comment]
I'm having a hard time seeing how this is going wrong due to locale with the current code.  The actual error is signaled here: https://github.com/tesseract-ocr/tesseract/blob/master/classify/clusttool.cpp#L89 which happens when it is unhappy with the results that tfscanf gets for the feature parameters. tfscanf is a private, locale-independent version of fscanf, which calls, in turn, the private tvfscanf which implements its own parsing of floats with a hard coded decimal separator of '.'

One thing that definitely could cause it though is a bad/corrupted feature parameter file.

I just tested with the stock tesseract 3.03 on a brand new Debian 8 installation with the locale set to fr_FR.UTF-8 and everything worked perfectly.

If you still can't get this to work, please post the output of the following commands:

    uname -a
    tesseract -v
    locale

**Comment by zdenop** [comment]
@oelleo: unfortunately tesseract requires (at the moment) training data use dot as decimal separator => you need to correct your custom training data.

I think it could be possible without retraining.  Try to unpack your data (`combine_tessdata -u eng.traineddata tmp/eng.`) and fix decimal separator in `eng.normproto` (replace eng with your name of your custom training)
