### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [tesseract-ocr/tesseract#98]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html)" to [your build specification](https://github.com/tesseract-ocr/tesseract/blob/c4d52c77becbe092410e5ebfdc8a2533b0bbe374/configure.ac#L385)?

**Comment by amitdo** [comment]
@stweil
Do you think we need this?

**Comment by stweil** [comment]
Using `AX_PTHREAD` would introduce a new dependency, because it is part of the GNU Autoconf Archive. On all of my build hosts, the Debian package `autoconf-archive` would have to be installed.

I only found a configure.ac for powertop which uses `AX_PTHREAD`, so it seems to be rarely used.

If we have multi-threaded code based on pthread, it is necessary to use the right compiler and linker options. Those options can be set by `AX_PTHREAD`, but also by software packages using pkg-config.

@elfring, did you notice missing options for pthread support in some Tesseract configurations?

**Comment by elfring** [comment]
>If we have multi-threaded code based on pthread, it is necessary to use the right compiler and linker options.

* Which script should determine appropriate parameters for [your current build specification](https://github.com/tesseract-ocr/tesseract/blob/4cbe9622d14572a460d27f5b1dbbce53d2e267fe/configure.ac#L386 "Configuration checks")?
* Would you like to bundle it with your build system?

**Comment by stweil** [comment]
I don't use any private scripts for compiler or linker options in Tesseract builds.

As far as I see, Tesseract only uses multi-threading for the viewer (only built for Windows, see `viewer/svutil.cpp` and for builds with OpenCL (which is disabled by default). So I assume that there is currently a problem with missing multi-threading compiler / linker options for these two configurations. Is that correct? Personally I must admit that I used neither of both configurations up to now.

**Comment by elfring** [comment]
Would you like to improve the build situation generally for the mentioned software areas?

**Comment by stweil** [comment]
Yes, of course, but I won't be able to contribute much during the next few weeks due to other activities.

**Comment by amitdo** [comment]
@elfring
I can't guarantee that there will be someone available to review these build system changes. I was hoping that @stweil could do it, but he has other priorities right now...

**Comment by amitdo** [comment]
Also note that we want to support cygwin and mingw.

**Comment by zdenop** [comment]
And we need to support Visual Studio ;-)

**Comment by zdenop** [comment]
Closing as it seems no progress for 2  years. Feel free to send PR with code/build system improvement.
