### ISSUE TITLE
extra spaces in result when ocr chinese

### ISSUE THREAD

**Issue by goodtogood** [tesseract-ocr/tesseract#991]
win8.1 64bit tesseract 4.0.0alpha  leptonica-1.74.2 (Jun  6 2017, 21:45:59) [MSC v.1910 LIB Release x64]

the reslut always contains extra spaces between character when using oem LstmOnly or TesseractAndLstm, oem TesseractOnly works normally but the result is bad. 

![image](https://user-images.githubusercontent.com/10088733/27135386-f6cd87b6-514a-11e7-85ce-4d825f14f471.png)

oem:  Default  psm: SingleLine  time: 114 ms.  result: 伦 敦 楼 房 发 生 火 灾 中 使 馆 关 注 : 暂 无 中 国 公 民 受 伤

oem:  TesseractOnly  psm: AutoOsd  time: 518 ms.  result:  伦敦夺委房发生火火中使馆大汪 二 暂无中 ` 又伤

 

[result_lines_chi.txt](https://github.com/tesseract-ocr/tesseract/files/1074793/result_lines_chi.txt)

**Comment by goodtogood** [comment]
@zdenop  @Shreeshrii @stweil 
can you guys give me some advice about  this ? thx.

**Comment by Shreeshrii** [comment]
@theraysmith Is there any config which will change this?

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/issues/988 regarding Japanese is also about similar results.

Could it be related in any way to handling of non-space delimited languages/CJK?

**Comment by Shreeshrii** [comment]
Possibly because of 

>>We also want to force a separate word for every non
      // space-delimited character when not in a dictionary context.

https://github.com/tesseract-ocr/tesseract/blob/a1c22fb0d0f6bde165ec7b7c3125420b0ba1d541/lstm/recodebeam.cpp

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1009

Similar problem with Korean.

**Comment by goodtogood** [comment]
there might be something wrong related to LSTM engine.

**Comment by hoangtocdo90** [comment]
sorry for my bad english
in my case Japanese  and OCR mode set to LTSM may by related .
i'm try to get single char only by using ResultIterator but sometimes final char in word doesn't have right coordinate. if change OCR mode to Tesseract Only it's okay.
Example :
大阪株式会社 
[debug] -Char value = 大 left= 16 top = 243 right = 68 bottom = 295 conf = 99
[debug] -Char value = 阪 left= 75 top = 244 right = 128 bottom = 295 conf = 99
[debug] -Char value = 株 left= 130 top = 244 right = 185 bottom = 296 conf = 99
[debug] -Char value = 式 left= 190 top = 243 right = 281 bottom = 296 conf = 99
[debug] -Char value = 会 left= 306 top = 243 right = 362 bottom = 296 conf = 99
[debug] -Char value = 社 left= 2214 top = 2991 right = 2214 bottom = 2991 conf = 99

**Comment by Shreeshrii** [comment]
Using the solution suggested in https://github.com/tesseract-ocr/tesseract/issues/1009
The extra spaces are removed and only inter-word-spaces are preserved.

See attached output files:

`--oem 1 --psm 6 -l chi_sim`
[chineses-1.txt](https://github.com/tesseract-ocr/tesseract/files/1108719/chineses-1.txt)


`--oem 1 --psm 6 -l chi_sim -c preserve_interword_spaces=1`

[spaces-spaces.txt](https://github.com/tesseract-ocr/tesseract/files/1108721/spaces-spaces.txt)

Please note that this is different from the behaviour of `preserve_interword_spaces` in 3.05 branch, where it preserves multiple spaces between words and does not compress them to single space.

@theraysmith  Is this intentional for 4.0? Since there are reports of `preserve_interword_spaces` not working with 4.0 - see https://github.com/tesseract-ocr/tesseract/issues/781

**Comment by goodtogood** [comment]
great, it works. Actually I noticed this variable, but I misunderstood and set it to false, definitely it doesn't work as expected. ~_~
> SetVariable("preserve_interword_spaces", false);

**Comment by hoangtocdo90** [comment]
@Shreeshrii  can you  help me ? i'm get wrong coordinate for last char in word. Thanks!

**Comment by Shreeshrii** [comment]
Sorry, @hoangtocdo90 . I do not know about `ResultIterator`

**Comment by Shreeshrii** [comment]
@jbreiden 

This fix can be applied via adding the following to the config file and then running combine_tessdata.

--------
# workaround to remove extra spaces in OCR result
# https://github.com/tesseract-ocr/tesseract/issues/991
preserve_interword_spaces 1
---------

This applies to Chinese, Japanese and Korean.

**Comment by Shreeshrii** [comment]
Fixed via 
https://github.com/tesseract-ocr/tessdata_fast/pull/7
https://github.com/tesseract-ocr/tessdata_fast/pull/8

@zdenop  Please close this issue, after PR is merged in tessdata_fast.

**Comment by xhuvom** [comment]
I am trying to train a new language with `ben.traineddata` . While providing sample training data with 
[lprBD-7.gt.txt](https://github.com/OCR-D/ocrd-train/files/2497559/lprBD-7.gt.txt) and .tif image, I am getting the error


`Can't encode transcription: '| ঢাকা মেটো-গ |' in language ''
Encoding of string failed! Failure bytes: ffffffe0 ffffffa6 ffffffbe ffffffe0 ffffffa6 ffffff95 ffffffe0 ffffffa6 ffffffbe 20 ffffffe0 ffffffa6 ffffffae ffffffe0 ffffffa7 ffffff87 ffffffe0 ffffffa6 ffffff9f ffffffe0 ffffffa7 ffffff8d ffffffe0 ffffffa6 ffffffb0 ffffffe0 ffffffa7 ffffff8b 2d 20 ffffffe0 ffffffa6 ffffff97 20 7c 20 ffffffe0 ffffffa5 ffffffa4
Can't encode transcription: '\ ঢাকা মেট্রো- গ | ।' in language ''
2 Percent improvement time=0, best error was 7.2 @ 271
At iteration 271/2700/153861, Mean rms=0.211%, delta=0%, char train=0%, word train=0%, skip ratio=5600%,  New best char error = 0 wrote best model:data/checkpoints/BigBenww0_271.checkpoint wrote checkpoint.`

What changes should be made in order to train a new language?

**Comment by stweil** [comment]
@Shreeshrii, I just want to add `preserve_interword_spaces 1` for tessdata and tessdata_best, too (see issue #2450). As far as I see, these files need to be fixed:

    tessdata/chi_sim/chi_sim.config
    tessdata/chi_tra/chi_tra.config
    tessdata/jpn/jpn.config
    tessdata/tha/tha.config
    tessdata_best/chi_sim/chi_sim.config
    tessdata_best/chi_tra/chi_tra.config
    tessdata_best/jpn/jpn.config
    tessdata_best/tha/tha.config

Is that correct?

**Comment by Shreeshrii** [comment]
@stweil Yes, that's right. Thank you.

**Comment by stweil** [comment]
I fixed `tessdata_best/jpn_vert/jpn_vert.config` which is included by `tessdata_best/jpn/jpn.config`.

**Comment by stweil** [comment]
What about `chi_sim_vert`, `chi_tra_vert`, `jpn_vert` in `tessdata_fast`. Do they need `preserve_interword_spaces=1`, too?

**Comment by ZetaLin** [comment]
@stweil actually,I used this method to extract the training data before I saw your article, but the pdf copy still had Spaces. That is to say, the exported txt does not have Spaces, but the pdf copy text still has extra Spaces. 

I should also note that another workaround is to use the congfig setting without having to modify the training data.
the command line:

`ocrmypdf  -l chi_sim --tesseract-config my.cfg input.pdf out.pdf
`
Where my.cfg is a local file: the contents are:

preserve_interword_spaces 1

**Comment by legistek** [comment]
@ZetaLin same issue here. The raw text output is right but when output to PDF there is a space between every character.

**Comment by languagemaniac** [comment]
> @stweil actually,I used this method to extract the training data before I saw your article, but the pdf copy still had Spaces. That is to say, the exported txt does not have Spaces, but the pdf copy text still has extra Spaces.
> 
> I should also note that another workaround is to use the congfig setting without having to modify the training data. the command line:
> 
> `ocrmypdf -l chi_sim --tesseract-config my.cfg input.pdf out.pdf ` Where my.cfg is a local file: the contents are:
> 
> preserve_interword_spaces 1

Does that still work for you? I tried that but it's not working for me., don't know what to do
